helium/oracles

- .github/scripts/packagecloud_upload.sh
Problem to solve: We were previously pushing packages into 3 private repos. We can now push all packages into one public repo.
> Update packagecloud upload path

- Cargo.lock
- mobile_rewards/Cargo.toml
- store/Cargo.toml
- store/src/file_sink.rs
The mobile rewards being too lenient with it's version of the rand crate is causing build problems with other dependencies that specify much older versions of the crate
> pin rand to a recent version

- .github/workflows/rust.yml
- Change order of `build` and `clippy` steps, do `build` first
- Add rust-cache CI step
Fix https://github.com/helium/oracles/issues/86
> Test cached CI

- poc_iot_verifier/migrations/3_poc_report.sql
- poc_iot_verifier/src/entropy.rs
- poc_iot_verifier/src/lib.rs
- poc_iot_verifier/src/loader.rs
- poc_iot_verifier/src/main.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/poc_report.rs
- poc_iot_verifier/src/purger.rs
- poc_iot_verifier/src/runner.rs
linked Proto PR: [andymck/add-stale-invalid-reason](https://github.com/helium/proto/pull/195)
Adds purging of stale data from the verifier postgres DB to prevent data growing unbounded
Cover 3 main scenarios:
1. Verified beacon and witness reports ( valid or invalid ), these are deleted from the DB immediately after verification and after the associated report is outputted to S3
2. Stale beacon and witness reports, these are reports which are not verifiable.  It could be a witness report which has no associated beacon report or a beacon report which has no associated entropy report.  These are purged after a defined period of time.
3. Entropy reports, these are deleted after a defined period of time 
I may still add a subsequent PR to better cater for the verifier being down for an …
> purge db of stale data

- Cargo.lock
- node_follower/src/error.rs
- node_follower/src/follower_service.rs
- node_follower/src/gateway_resp.rs
- node_follower/src/lib.rs
- node_follower/src/txn_service.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
- poc_mobile_verifier/src/reward_share.rs
The addition of a "GatewayNotFound" response to the follower node GRPC API requires a restructuring of the response struct received by clients of the service querying the `find_gateway` RPC; this change adapts to the new proto structure to handle the possibility the gateway is not found and converts it to an appropriate error in that situation.
> realign follower proto response with new structure

- Cargo.lock
- Cargo.toml
- density_scaler/Cargo.toml
- density_scaler/README.md
- density_scaler/src/error.rs
- density_scaler/src/hex.rs
- density_scaler/src/lib.rs
- density_scaler/src/query.rs
- density_scaler/src/server.rs
- node_follower/Cargo.toml
- node_follower/src/error.rs
- node_follower/src/follower_service.rs
- node_follower/src/lib.rs
implement a density scaling crate; the density_scaler runs as a separate tokio process within a service. it schedules a recurring process at a regular interval that queries a blockchain-node, retrieves the h3dex index location of all active gateways over a grpc stream and computes the scaling factor for all res 11 hexes, storing them in a wrapped hashmap. the scaler process also provides a query api wrapped around message channels for communicating between the calling service and the scaler.
> density scaler crate

- Cargo.lock
- db_store/Cargo.toml
- db_store/src/lib.rs
- entropy/src/entropy_generator.rs
- entropy/src/server.rs
- file_store/Cargo.toml
- file_store/src/file_sink.rs
- file_store/src/file_store.rs
- ingest/src/server_5g.rs
- ingest/src/server_lora.rs
- metrics/src/lib.rs
- poc_iot_verifier/src/purger.rs
- poc_iot_verifier/src/runner.rs
- poc_mobile_verifier/src/heartbeats.rs
- poc_mobile_verifier/src/speedtests.rs
- poc_mobile_verifier/src/subnetwork_rewards.rs
Summary:
1. instruments:
- `file_store::file_store::{put, remove}` to:
- __time__ writes to AWS (reads timing is less clear, since it returns a stream)
- `file_store::file_sink::write` to:
- __count__ all successes and failures
- `db_store::{insert, fetch_or_insert_with, update}` to:
- __count__ all successes and failures
- __time__ execution durations
2. updates all affected call sites with the newly-required static tag
3. extends `poc_metrics::ActiveRequests` layer to also __time__ request handling durations (renaming it to simply `poc_metrics::Requests`) in addition to __counting__ currently active connections that it was already doing
4. updates the metrics layer usage in:
- `ingest::server_5g`
5. adds the metrics layer to:
- `ingest::server_lora`
- `entropy::server`
> Instrument IO

- poc_mobile_verifier/src/speedtests.rs
- poc_mobile_verifier/src/subnetwork_rewards.rs
incorporate the rolling speedtest averages, when available, into the mobile rewards calculation for hotspots. when a speedtest rolling average cannot be calculated (the minimum number of speedtests have not been submitted within the required period) then the multiplier for speedtests defaults to 0.0 (decimal) and the hotspot does not receive any rewards for the reward cycle.
> factor speedtest averages into mobile rewards

- poc_mobile_verifier/src/cli/server.rs
the mobile verifier is currently not exporting metrics; we're going to want those
> add prometheus exporter to mobile verifier

- poc_mobile_verifier/src/subnetwork_rewards.rs
we don't want to be including subnetwork reward entries in the final proto submitted to the reward server that have 0 shares b/c the owner/hotspot was disqualified for not meeting speedtest criteria (frequency and number of data points). this filter operation will weed out any subnetwork reward share entries that would not be receiving rewards for a given period.
> filtering 0-rewards from reward results

- db_store/src/lib.rs
- db_store/src/meta.rs
- poc_mobile_verifier/src/cli/server.rs
- poc_mobile_verifier/src/verifier.rs
So I wanted to simplify the db access and move the responsibility into a single entity.
Current downside, if the 3 values `last_verified_end_time`, `last_rewarded_end_time`, and `next_rewarded_end_time` are not in the meta table it will crash the server.
> Simplify db access in poc_mobile_verifier

- poc_mobile_verifier/src/speedtests.rs
- poc_mobile_verifier/src/subnetwork_rewards.rs
- poc_mobile_verifier/src/verifier.rs
we need to save up to 6 (current maximum data points for calculating speedtest averages) in the database but still ensure that speedtests that have a lapse period greater than the allowable window are _not_ included in average calculations when determining rewards and are _not_ written in reports to the verifier output bucket.
the following extends the maximum window the database looks for when querying saved speedtests for performing average calculations from 12 to 48 hours to ensure we capture a minimum of 2 speedtests if they are present (with a generous buffer to allow for randomness in the speedtest submission logic) as well as to filter out speedtests from the speedtest averages data structure before performing a write of average reports to s3 and calculating reward share weights. …
> push lapsed speedtests filter to write/reward time

- poc_mobile_verifier/src/speedtests.rs
tests functionality of the `SpeedtestAverages` impl of `IntoIter` to ensure the iterable `SpeedtestRollingAverages` all convert to storing the order of the speedtests under it's key of the same name with the newest at the front of a VecDeque when traversing from the right to the left and the timestamp of this first/left-most speedtest is also recorded as the `last_timestamp` field defined on the `SpeedtestRollingAverage` struct
> test speedtestavg into_iter timestamps/ordering

- poc_mobile_verifier/src/speedtests.rs
- poc_mobile_verifier/src/verifier.rs
moves the transformation of speedtest iterators from an impl method on the SpeedtestAverages struct to a free function that takes and returns an `Iterator<Item = &'a Speedtest>`. this allows us to keep the logic of the transformation isolated to the speedtests module and call it within the publicly exported functions that execute speedtest calculations elsewhere in the oracle such as when computing the subnetwork rewards.
> move old speedtest filter to iterator transformer

- poc_iot_verifier/README.md
- poc_iot_verifier/src/entropy.rs
- poc_iot_verifier/src/last_beacon.rs
- poc_iot_verifier/src/loader.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/poc_report.rs
- poc_iot_verifier/src/runner.rs
- fix ambiguous columns issue on report query
- Adds on conflict clause to ignore duplicate poc report and entropy report inserts
- Adds max age for consuming events from s3 ( beacon/witness report or entropy report ).  Ignore reports outside of this age
- Adds check to incoming beacon and witness reports to identify if unknown gateway.  If true the drop the report
- Code tidy up
> misc fixes

- file_store/src/file_info.rs
- poc_iot_injector/src/cli/generate.rs
- poc_iot_injector/src/error.rs
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_injector/src/server.rs
- poc_iot_injector/src/settings.rs
- poc_mobile_verifier/src/subnetwork_rewards.rs
This adds support for writing poc receipt txns to s3 bucket once they have been submitted to the chain.
- The if-else clauses could use some scrutiny
- Am I actually writing the txn correctly to S3? I mostly looked through poc_mobile_verifier for depositing the file
> Add support for storing receipt txns on S3

- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/poc_report.rs
- poc_iot_verifier/src/runner.rs
- poc_mobile_verifier/src/subnetwork_rewards.rs
- Eliminate an unnecessary entropy DB read.  Instead, include the necessary entropy start time in the DB query response when pulling the list of next beacons to be verified
- Related to above, remove the beacon verification to check entropy exists.  If a beacon report exists for which no entropy exists, then it will not be returned in the query to retrieve beacons anyway and instead will eventually be purged.  As such for any beacon returned for verification we can be sure entropy *does* exist and as such the validation is unnecessary
- Move beacon interval verification from the runner to the POC impl.  Keeps all verifications in one central place.
- Tidy up how the `follower_service` is passed from the runner to the POC impl
> verification cleanup

- poc_iot_verifier/migrations/6_add_entropy_start_time.sql
- poc_iot_verifier/migrations/6_entropy_start_time.down.sql
- poc_iot_verifier/migrations/6_entropy_start_time.up.sql
- poc_iot_verifier/src/poc_report.rs
Fixes some bugs with the `poc_report` query we found during deployment.
> Fix poc_report join query and add entropy_start_time migration

- poc_iot_injector/src/receipt_txn.rs
Found this while generating poc receipt transactions locally using the latest valid reports from mainnet.
> Dont error out on zero witnesses

- poc_iot_injector/pkg/deb/settings-template.toml
- poc_iot_injector/src/cli/generate.rs
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_injector/src/server.rs
- poc_iot_injector/src/settings.rs
This adds an extra setting `do_submission` boolean flag to specify whether to submit txn to mainnet. Mostly because we want to start the injector but don't really want to start submitting txns to mainnet just yet.
> Add an additional setting for txn submission

- file_store/src/file_sink.rs
Changing file_sink  missed tick behaviour to Burst, logically I don't think it makes sense to Delay a missing tick. Delay would mean we just wait 3 more minutes to check the time of the ActiveSink.  Better to check the time of the ActiveSink as soon as we can.  We will setup timing between ingest/verifier/rewards so that a large delay over the configured roll time could cause issues.
> Changed file_sink missed tick behavior to Burst

- poc_iot_injector/src/cli/server.rs
- poc_iot_injector/src/server.rs
Fix for deploy attempt #2. Actually use the sender part of the file sink instead of creating a new one on the fly.
> Use the correct receipt sender for file_sink

- Cargo.lock
- Cargo.toml
- poc_iot_verifier/Cargo.toml
- poc_iot_verifier/src/poc_report.rs
- poc_iot_verifier/src/runner.rs
Downgrades logging of witness count to debug level to reduce noise at high report volume
Remove the limit on number of beacons to process
( might be warranted to reintroduce this at some point but i want to see the true report count per tick )
> logging level tweaks and remove limit on beacon count

- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
- fix DB report id when updating beacon status to valid ( fixes issue where beacon reports would be reverified )
- fix hardcoded InvalidReason for invalid beacons ( use the returned reason )
- extend entropy lifespan, give more time for hotspots to submit reports
- add grace/tolerance to beacon interval verification, allow for clock drift between client and server
- add tmp info level logging
> Tweaks & Fixes from mainnet testing

- file_store/src/lora_valid_poc.rs
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_injector/src/server.rs
This removes a bunch of hand rolled decoding done for valid pocs. It now just uses the existing structs in file_store to do the same.
Still doesn't seem to be working. Error when dumping the valid_poc file using file store is the same when running the injector on prod:
```bash
cargo run --release -- -c settings.toml dump lora_valid_poc lora_valid_poc.1668036372924.gz
Finished release [optimized] target(s) in 0.26s
Running `/home/rahul/dev/oracles/target/release/file-store -c settings.toml dump lora_valid_poc /home/rahul/dev/oracle-output/valid-pocs/lora_valid_poc.1668036372924.gz`
Error: Decode(Prost(DecodeError { description: "invalid wire type: ThirtyTwoBit (expected Varint)", stack: [("LoraValidBeaconReportV1", "hex_scale"), ("LoraValidPocV1", "beacon_report")] }))
```
I think its …
> Use existing structs for constructing valid pocs

- Cargo.lock
- Cargo.toml
- denylist/Cargo.toml
- denylist/src/client.rs
- denylist/src/denylist.rs
- denylist/src/error.rs
- denylist/src/lib.rs
- denylist/src/models/metadata.rs
- denylist/src/models/mod.rs
- denylist/src/settings.rs
- file_store/src/error.rs
- poc_iot_verifier/Cargo.toml
- poc_iot_verifier/pkg/deb/settings-template.toml
- poc_iot_verifier/src/error.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
- poc_iot_verifier/src/settings.rs
Adds support for denylist verification for beacon and witness reports.  
The denylist is fetched from github on startup and then periodically checked for updates.   
Once a denylist has been fetched from github, the filter will be saved locally.  Next time the verifier is restarted, this locally saved filter will be used as the initial filter during init and replaced with any newer version from github.
This enables a default filter to always be in use should github be unreachable for whatever reason.
> denylist verification for witness and receipt reports

- poc_mobile_verifier/src/heartbeats.rs
This prevents an owner from cheating by switching a radio to another hotspot during a reward period
> Delete heartbeats if a radio was moved to a new hotspot

- file_store/src/file_sink.rs
- poc_ingest/src/server_5g.rs
- poc_mobile_verifier/deb/settings-template.toml
- poc_mobile_verifier/src/cli/server.rs
- poc_mobile_verifier/src/scheduler.rs
- poc_mobile_verifier/src/settings.rs
- poc_mobile_verifier/src/verifier.rs
1. mobile ingest will now wait up to 15 minutes before uploading `heartbeat_report` or `speedtest_report` to S3
2. poc_mobile_verifier will wait up to 15 minutes before uploading `validated_heartbeat` or `speedtest_avg` to S3
3. poc_mobile_verifier will now run verify and reward cycles offset from the period by 30 minutes. Example: for the verification period 01:00 to 04:00, verification will run at 04:30
4. poc_mobile_verifier will flush rewards file and upload to S3 at end of reward cycle, not waiting for the rolling period, since it is known that there is no more data.
> Change timings of mobile pipeline

- poc_iot_verifier/src/purger.rs
Uses concurrent streams to purge the DB of stale beacon and witness reports
It also actually fixes the purging, as previously the purge did not take place as i misunderstood the lazy quality of map when originally implementing this.  Also fixes other bugs relating to the DB report ID
> purge db using streams

- Cargo.lock
- denylist/Cargo.toml
- denylist/src/settings.rs
- poc_iot_verifier/src/loader.rs
- poc_iot_verifier/src/main.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
This moves the denylist check to the edge.  The check will now be performed at the point the report is loaded from s3 and prior to inserting to the DB ( verifications are mostly run post DB insert and on data taken directly from the DB ).  This prevents any report from a denied hotspot from making it to the DB and consuming additional resources
> run denylist check pre db insert

- Cargo.lock
- file_store/src/lora_valid_poc.rs
- poc_iot_injector/Cargo.toml
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_verifier/Cargo.toml
- poc_iot_verifier/src/error.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
We need to continue to calculate the total IoT reward shares as a factor (in part) of the number of witnesses to a PoC event but should be doing so in the IoT Verifier so as to be able to keep the logic in the (temporary) IoT receipt Injector light and to allow for easily calculating the full reward shares within the verifier when submitting to the reward indexer for Solana integration.
This change migrates the calculation of the reward unit value from the injector to the verifier. It adds the value as a new field on the valid beacon and witness structs as well as the accompanying proto definitions as part of this dependent PR https://github.com/helium/proto/pull/234
> move reward unit calculations to iot verifier

- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
ensure that these two math operations are handled safely so they don't cause horrible performance problems
> fix maths underflow

- poc_iot_verifier/src/runner.rs
This fixes the updating of a hotspots last beacon time in the DB which as accidentally removed as part of the recent optimisation branch resulting in a hotspot's last beacon time not being recorded.
> put back last beacon time updates

- .github/workflows/rust.yml
- poc_mobile_verifier/src/owner_shares.rs
- poc_mobile_verifier/src/scheduler.rs
- poc_mobile_verifier/src/speedtests.rs
There are quite a few Clippy warnings for tests. This PR is two-phase: 
1. [x] turn on `--all-targets` for the Clippy CI step and make sure the build fails
https://github.com/helium/oracles/actions/runs/3634343994/jobs/6132332422#step:7:341
3. [x] push fixes and ensure CI succeeds.
> Lint all targets

- poc_iot_verifier/src/loader.rs
This fixes an issue encountered on mainnet whereby the processing of report files loaded from s3 takes longer than the tick time resulting in some s3 files being skipped.
The sliding window used by the loader had a fixed width in minutes,  equal to our tick time and a max age for its starting position equal to tick time * 2.   Normally the start point for the window is the end point of the window position during the previous tick.  However when the processing of a previous batch of files exceeds the tick time the next window start point would be greater than the max age and the window would be shuffled forwards, skipping some time and any files on s3 for that skipped period.
With this fix the sliding window start point continues to be the endpoint of the previous window position but the …
> fix loader sliding window

- density_scaler/src/hex.rs
- poc_iot_verifier/src/poc.rs
If this PR is fine, it will remove **a lot** of heap allocations and reduce RAM usage.
> perf: remove unneeded string conversion

- Cargo.lock
- density_scaler/src/server.rs
this change pulls in an update to the helium-proto dependency with support for a missing region (`RU864`) as well as moves/increases some debugging statements surrounding the construction of the hex scaling factor map the density_scaler produces for IoT PoC calculations
> update proto for new region; scaling factor debugging

- poc_iot_verifier/src/main.rs
- poc_iot_verifier/src/rewarder.rs
the PRs that introduced the IoT reward shares calculations in the IoT verifier got wires crossed with the one that updated the file_sink API to introduce more txn-like semantics to writing out files to the sink. This should fix that error that's currently breaking the main build.
> reconcile iot reward shares with updated file_sink api

- Cargo.lock
- density_scaler/src/error.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
This makes hex scaling factor another validation check, requiring for the density scaler to have found a valid scaling factor decimal for the asserted gateway's hex location. Depends on https://github.com/helium/proto/pull/241 being merged to clean up the branch reference in the root cargo file.
Also performs some minor error handling cleanup related to the previous channel-based implementation of the density scaler.
> move hex scaling factor to validation check

- poc_iot_injector/src/cli/construct.rs
- poc_iot_injector/src/cli/mod.rs
- poc_iot_injector/src/main.rs
This adds a new CLI `construct` for basically constructing poc receipts txns from an input lora_valid_poc file. This is largely for debugging since we have the `generate` CLI as well but that has dependency on setting up local minio for FileStore.
> Add support for constructing receipt txn from valid_poc file

- poc_iot_verifier/migrations/6_gateway_shares.sql
- poc_iot_verifier/migrations/7_bootstrap_reward_time.sql
the iot verifier reward schedule needs to be kicked off with a value in the database that allows it to gauge at the next reward interval if it's time to process rewards again or not. we determined the best approach was to add a one-time entry to the database via a migration
> adding a bootstrap timestamp to iot verifier meta table

- file_store/src/lora_valid_poc.rs
this change corrects a mismatch in the amount of precision being applied to hex scaling factors and reward units when they are serialized to protobuf as u32s for transit over the wire and then back again to decimals on the other side.
we are applying 4 places of decimal precision when creating the decimal value but when converting to a u32 we have not been multiplying by the correct factor to re-initialize the desired decimal value on the other side of the report proto conversion
> correctly convert decimals back and forth

- Cargo.lock
- Cargo.toml
- denylist/src/denylist.rs
- file_store/src/cli/bucket.rs
- file_store/src/file_store.rs
- file_store/src/heartbeat.rs
- file_store/src/lora_beacon_report.rs
- file_store/src/lora_witness_report.rs
- file_store/src/speedtest.rs
- file_store/src/traits/report_id.rs
- node_follower/src/follower_service.rs
- node_follower/src/gateway_resp.rs
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_verifier/Cargo.toml
- poc_iot_verifier/migrations/3_poc_report.sql
- poc_iot_verifier/src/entropy_loader.rs
- poc_iot_verifier/src/gateway_cache.rs
- poc_iot_verifier/src/last_beacon.rs
- poc_iot_verifier/src/lib.rs
- poc_iot_verifier/src/loader.rs
- poc_iot_verifier/src/main.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/poc_report.rs
- poc_iot_verifier/src/purger.rs
- poc_iot_verifier/src/reward_share.rs
- poc_iot_verifier/src/runner.rs
- poc_mobile_verifier/src/heartbeats.rs
- poc_mobile_verifier/src/owner_shares.rs
- poc_mobile_verifier/src/speedtests.rs
This adds a bunch of optimisations to the loading of reports.  The main optimisations include:
1.  PublicKeyBinary: default public key to binary type rather than the full public key type ( this change is applied to all oracles )
2. Bulk insert of beacon and witness reports to DB and handle inserts via a transaction
3. Use an xor filter of beacon packet data, use filter to verify witness reports have an associated beacon before inserting to DB.  If no associated beacon report drop the witness report.  This siphons out a significant amount of spurious witness reports from clients
4. Process file load per file and add transaction support.  Concurrently process reports on a per file basis
Some misc other changes include
1. Separate loading of entropy and reports.  run each in this own thread …
> loader optimisations and fixes

- Cargo.lock
- density_scaler/src/error.rs
- poc_iot_verifier/src/poc.rs
- poc_iot_verifier/src/runner.rs
Refactor of the `poc` module to break up long winded functions and to break out the beacon and witness verifications to independently testable functions.  It then adds unit tests for each such verification.
I was planning on also adding tests for the poc struct and confirm the input and outputs of an overall poc but i need more planning for those and how to work around the lack of a follower etc.  That can come later as a sep PR, this is already long enough as it is in any case.
> refactor of poc module and unit tests for each verification

- Cargo.lock
- Cargo.toml
- iot_verifier/src/gateway_cache.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/purger.rs
- iot_verifier/src/runner.rs
This addresses an issue with how the refactored POC module handled errors after the prior merged `anyhow` changes.
If the handling of any one of N witnesses for a beacon resulted in an error ( such as when a witness has no asserted location ) then that would halt any further processing of remaining witnesses and also result in the beacon itself failing to complete verification.
The DB would also not be updated to bump the `attempts` count on either the failing witness or associated beacon and thus the POC would get stuck in a loop of being verified and failing each tick until they end up being purged by the purger.
Thus this PR makes the following logic assumptions:
1.   `poc::verify_beacon` and `poc::verify_witnesses` will return Result<VerifyResult, VerificationError>. …
> Fix witness error handling

- poc_iot_injector/pkg/settings-template.toml
- poc_iot_injector/src/cli/construct.rs
- poc_iot_injector/src/cli/generate.rs
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_injector/src/server.rs
- poc_iot_injector/src/settings.rs
- Add `max_witnesses_per_receipt` setting. Default = 14.
- Maybe squish poc_witnesses if the length of witnesses is > max_witnesses_per_receipt. Seed a random number from the poc_id for shuffling the witnesses and truncating the witnesses
> Add support to squish witnesses per receipt

- node_follower/src/txn_service.rs
- Fallback to singular client in txn_service if multiple submissions is not configured.
> Avoid no grpc error

- iot_verifier/src/poc.rs
- iot_verifier/src/poc_report.rs
- iot_verifier/src/purger.rs
- Adds conflict strategy for bulk inserts. If the verifier is abruptly shutdown or crashes there is a potential to reload reports which were previously loaded.  Without the `conflict` strategy we get a lot of noisy errors polluting the logs
- Extends expected beacon interval from 10 mins to 6 hours and define beacon intervals as duration rather than i64s
- Explicitly define beacon interval tolerance and enhance related test
- Set interval before a stale beacon or witness report is purged to the same value
> Timing related tweaks and conflict support for bulk inserts

- iot_config/src/main.rs
enable grpc keepalive for config server long-lived streams to prevent load balancer from culling stale connections during inactive periods
> introduce grpc keepalive settings for config

- Cargo.lock
- Cargo.toml
- poc_entropy/Cargo.toml
- poc_entropy/src/entropy_generator.rs
- poc_entropy/src/lib.rs
- poc_entropy/src/multiplex_service.rs
- poc_entropy/src/server.rs
As part of migrating to grpc only for entropy, this PR supports both REST and GRPC requests for poc_entropy against the same host/port. It will allow gateway-rs to request entropy over grpc.
Note that this implementation serves both GRPC and REST requests over the same port, and auto-dispatches to the right handler based on request headers.
Once the majority of hotspots have upgraded to a gateway-rs release that includes https://github.com/helium/gateway-rs/pull/348 the reset service  can be removed and tls termination decommissioned. 
While they are not however, the entropy service needs to continue to be available on `http://entropy.helium.io` as well as `https://entropy.helium.io`. See the [current and new setup change](https://github.com/helium/gateway-rs/pull/348/files#diff-7d0e50ed26 …
> Support both grpc and rest api for poc_entropy

- Cargo.lock
- Cargo.toml
- docker-compose.yml
- file_store/src/traits/msg_verify.rs
- iot_config/src/main.rs
- iot_config/src/org.rs
- iot_config/src/org_service.rs
- iot_config/src/route_service.rs
- iot_config/src/settings.rs
adds basic admin validation of requests to create organization entities; lays foundation for further admin pubkey validation of routing and session key filter management requests.
also consolidates proper deserialization and network validation for submitted owner/payer and delegate keys
implements http2 keepalive interval and timeout for grpc server to prevent long-lived streams from being culled by the load balancer
> org and route request auth on config service

- iot_verifier/src/loader.rs
- iot_verifier/src/metrics.rs
Adds metrics to track the number of reports we drop to the floor due to:
1. Gateway being on the deny list 
2. Gateway not found 
3. Witness report not having any associated beacon data
> add metrics to cover denied and unknown gateways dropped during loading

- poc_iot_injector/src/receipt_txn.rs
For a witness, this change would effectively give back:
```
timestamp: 1673546588,
signal: -120,
packet_hash: [...],
signature: [],
snr: -5.2,
frequency: 905.1,
channel: 0,
datarate: "SF12BW125",
reward_shares: 200,
```
previously:
```
timestamp: 1673546588,
signal: -1200,
packet_hash: [...],
signature: [],
snr: -52,
frequency: 905.1,
channel: 0,
datarate: "SF12BW125",
reward_shares: 200,
```
> Ensure that snr and signal are of correct units

- iot_verifier/pkg/settings-template.toml
- iot_verifier/src/poc.rs
- iot_verifier/src/runner.rs
- iot_verifier/src/settings.rs
This removes the constant `BEACON_INTERVA`L and `BEACON_INTERVAL_TOLERANCE` and makes it configurable via settings.
> Make beacon_interval & beacon_interval_tolerance configurable

- iot_verifier/src/poc.rs
- poc_iot_injector/src/receipt_txn.rs
This PR:
- Ensures that invalid witnesses get zero reward units
- Removes extra checks for zero reward shares on injector level, since the chain has protection for it with `zero_reward_shares_fix` var
> Make sure that invalid_witnesses get zero reward_units

- poc_iot_injector/pkg/settings-template.toml
- poc_iot_injector/src/server.rs
- poc_iot_injector/src/settings.rs
This adds a `submission_offset` (secs) setting to injector to offset receipt submission interval. This should ensure that we capture all the files written to S3, previously we would potentially skip S3 files which were still being written to.
> Add submission_offset setting for receipt submission

- Cargo.lock
- iot_config/src/gateway_service.rs
- iot_config/src/region_map.rs
This PR:
- upgrades the hextree to 0.2.0
- moves a validity check out of a hot loop
- replaces using of `h3ron::H3Cell` with `hextree::Cell`
Not that this PR targets @jeffgrunewald's branch, not main.
> [iot-config] upgrade hextree

- Cargo.lock
- iot_verifier/src/poc.rs
depends on https://github.com/helium/proto/pull/274
Adds a missed verification to determine the witness is located a minimum number of cells from the beaconer.  If not the witness will be declared invalid
The test data was run via the blockchain core code using its h3 implementation in order to sanitise the input and results.
> verify min cell distance between beaconer and witness

- poc_iot_injector/pkg/settings-template.toml
- poc_iot_injector/src/server.rs
- poc_iot_injector/src/settings.rs
This adds a max age at which the injector can look back for files from S3.
> add max file age for injector loading

- poc_iot_injector/src/receipt_txn.rs
this is a hack to override the unused channel field of the witness_v1 proto with the enum value of the verifier assigned invalid reason.   ETL will then inspect this onchain data for any witness with 0 reward shares and use any non zero `channel` value as the reason why the witness is invalid.  Explorer can then depict the specific invalid reason on the UI
Linked core pr: https://github.com/helium/blockchain-core/pull/1525
NOTE: this is a known hack.  It is only meant to be temporary and will be dropped post current l1 transition ( along with the injector )
> override channel to hold witness verification status

- db_store/src/settings.rs
When not specified the database connection settings are pulled from the following environment variables. Note that using this approach removes the ability to have multiple db connections sections in the same settings file.
* `PGHOST`
* `PGPORT`
* `PGUSER`
* `PGPASSWORD`
* `PGDATABASE`
* `PGSSLROOTCERT`
* `PGSSLMODE`
* `PGAPPNAME`
> Allow db url to be optional

- Cargo.lock
- mobile_rewards/src/server.rs
- poc_iot_injector/Cargo.toml
- poc_iot_injector/pkg/settings-template.toml
- poc_iot_injector/src/receipt_txn.rs
- poc_iot_injector/src/server.rs
- poc_iot_injector/src/settings.rs
Summary
----
- Rate limit submission of poc receipt txns from the injector to chain.
- This is done using the [governor](https://crates.io/crates/governor) crate.
- The `max_txns_per_min` is configurable via settings (default = 2000)
TODO:
> Implement rate limit for poc receipt txns

- Cargo.lock
- node_follower/src/gateway_resp.rs
the mismatch between the current proto version of the gateway_info_resp message and the one on main for oracles is preventing updates of other areas of the oracles project that require the latest proto changes; this shims the missing piece into line to allow the oracle to be updated for any other patches needed in the wake of off-chain activation
> patch oracles for proto version changes

- Cargo.lock
- Cargo.toml
- file_store/src/traits/msg_verify.rs
- iot_config/Cargo.toml
- iot_config/migrations/4_regions.sql
- iot_config/pkg/settings-template.toml
- iot_config/src/gateway_service.rs
- iot_config/src/lib.rs
- iot_config/src/main.rs
- iot_config/src/region_map.rs
- iot_config/src/settings.rs
Implements the gRPC APIs for IoT gateways to connect and request their asserted location's region and region params, as well as the API for the admin user of the Config service to (re)load region params and region hex lists into the config server, persisting them to the DB
- Loading region params changes and region hex index lists to the service requires the request being signed by the registered "admin" keypair
- Region params and H3idx lists of region hex res 7 indexes are persisted to the DB as bytea fields, in-memory they are wrapped together in a `RegionMap` struct that consists of a `HexTreeMap<Region, EqCompactor>` (for efficient mapping of each asserted location's lorawan region), and a `HashMap<Region, BlockchainRegionParamsV1>`
> IoT Config service gateway region params rpc

- file_store/src/traits/msg_verify.rs
- iot_config/src/main.rs
- iot_config/src/org.rs
- iot_config/src/org_service.rs
- iot_config/src/route.rs
- iot_config/src/route_service.rs
Implement the config service's `enable` and `disable` org RPCs to allow the packet verifier to disable orgs and have their routes cascade-removed from the downstream helium packet routers when they run out of DC to pay for routing and allow re-enabling the orgs to cascade-recreate their routes when funds are replenished.
This change necessitates cloning the router service's ~~Arc-wrapped~~ broadcast channel transmitter to allow it to broadcast to subscribed packet routers when an org's status changes, thereby deleting or creating the routes registered to those orgs from the routing infrastructure
> handle enable and disable org rpcs

- Cargo.lock
- poc_iot_injector/Cargo.toml
- poc_iot_injector/src/receipt_txn.rs
We've noticed that `reward_shares` sometimes are incorrectly getting zero-ed out because of very low hex_scale values coming from the verifier.
This scales up the `REWARD_SHARE_MULTIPLIER` to `10000` to ensure that unless either hex_scale or reward_unit is very very low (0.0009 for example), the hotspots would still get some rewards.
The blockchain itself does not care what the multiplier is because its unit independent but we have to be careful when deploying this to ensure that we don't get blocks with mixed reward_share scales.
> Scale up reward_share_multiple by 100x

- iot_verifier/src/loader.rs
When loading witnesses the loader will take the beaon's window start/end times and widen it so that we load the roll up files not just for the same period as the beacons but those rolls up to the left and right of the beacons.
This is to ensure we do not miss witnesses which were included in a roll up just prior or after that of the beaconers.
The period of time the witness window should be widened by should be at least equal to that of the ingestor roll up time.  This was not the case with the current settings.  The ingestor roll up time is 5 mins, whilst the verifier was only widening the witness window by 2 mins on each side.
This fixes that by adding widening the witness window on both ends by the ingestor roll up time ( currently 5 mins )
A side effect of this change is that it would …
> widen witness loaded window to be > ingestor roll up time

- iot_verifier/src/metrics.rs
- iot_verifier/src/runner.rs
When we switched to the iot verifier performing the final 14 witness selection we broke the metrics for invalid witnesses.
Prior to this change, invalid witnesses were all written directly to S3 via their own invalid_witness proto.  The write function of the filestore took care of firing a metric for each file written to the sink.  
Post the above change however invalid witnesses form part of the `poc` proto, where invalid and valids make up the `poc` proto's `selected` and `unselected` lists.  This means the invalids now bypass the existing filestore metric generation.
This PR fixes the issue by firing the same metric as previously but from outside of the filestore and from the runner directly.  The filestore metric remains in place as there are other uses cases for it including the …
> write out metrics for invalid witnesses directly from runner

- Cargo.lock
- file_store/src/traits/msg_verify.rs
- iot_config/migrations/3_routes.sql
- iot_config/src/gateway_service.rs
- iot_config/src/lora_field.rs
- iot_config/src/route.rs
Requires merging https://github.com/helium/proto/pull/284 first.
Renames the load region params req/res to conform to the convention used by the other iot_config rpc messages by prepending each message with the name of the service it corresponds with.
This makes the proto encoding of the `hex_indexes` field in the region loading rpc non-optional from the perspective of proto3 but still allows it to be an optional argument by the config service operator.
> make idz file non-optional for proto3

- Cargo.lock
- file_store/Cargo.toml
- file_store/src/error.rs
- file_store/src/file_info_poller.rs
- file_store/src/file_source.rs
- file_store/src/incoming_data.rs
- file_store/src/lib.rs
This will poll s3 for new files on a short duration , but keep track of each individual file so it can handle files coming out of order.  The service will receive an already decoded stream over a channel when a new file is seen in s3.
The benefit of this is we will not have to make sure to have certain offsets configured based on the previous service's roll time on its output files.
Table definition
```
create table files_processed (
file_name varchar primary key,
file_type varchar,
file_timestamp timestamp,
processed_at timestamp
)
```
Configuration:
`start_after` --> the start point when querying into s3.  Will only be used when no records are found in the db.
`max_lookback` --> the max it will look back from now when querying s3.
Having both set doesn't really make sense, do we need …
> New module to stream FileInfoStream from s3

- file_store/src/iot_beacon_report.rs
- iot_verifier/src/poc.rs
This addresses a mismatch on the beacon generation on the verifier with that of the beacon generation on hotspots where the resultant generated data payload values did not match.
The root cause of the issue was that the verifier was passing in millisecs precision for its remote entropy timestamp value when generating the beacon to verify whereas the hotspots uses seconds precision.
> Use seconds precision for entropy timestamp.  Use hotspot generated entropy inputs and outputs for beacon verification test

- Cargo.lock
- file_store/src/iot_valid_poc.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/poc_report.rs
- iot_verifier/src/runner.rs
Address duplicate witness reports received for any one individual beacon and includes a slight refactor of witness verification flow.
The first witness report from any one gateway is accepted.  Any subsequent report from the same gateway for the same beacon will be rendered invalid with reason 'duplicate'.  Verifications will not be run on duplicates.
Reports marked as duplicate will be excluded from the last 14 and will make it to S3 as part of the `unselected` list.
There are multiple ways to handle duplications but the key considerations are:
1.  Do we require a report to make it to S3 for any witness rendered a dup ?
2.  In the scenario whereby we have both a valid and N invalids report from the same gateway....which one is deduped ?  How do we decide on that ?  
3. In the scenario …
> invalidate dup witness reports

- iot_config/src/gateway_service.rs
- poc_iot_injector/src/receipt_txn.rs
Summary
----
This PR is to attach `hex_scale` and `reward_unit` to poc receipts and poc witnesses present in the poc receipt txns.
Depends on [helium-proto#280](https://github.com/helium/proto/pull/280).
Notes
----
- Attach the `hex_scale` and `reward_unit` on txn construction
- Before signing the txn, zero out both of those fields
- Re-attach the originally constructed path back to the signed txn
TODO
----
> Attach hex_scale and reward_unit to poc receipt txns

- Cargo.lock
- Cargo.toml
- docker-compose.yml
- file_store/src/traits/msg_verify.rs
- iot_config/migrations/5_admin_keys.sql
- iot_config/migrations/5_hpr_keys.sql
- iot_config/src/admin.rs
- iot_config/src/admin_service.rs
- iot_config/src/gateway_service.rs
- iot_config/src/lib.rs
- iot_config/src/lora_field.rs
- iot_config/src/main.rs
- iot_config/src/org.rs
- iot_config/src/org_service.rs
- iot_config/src/region_map.rs
- iot_config/src/route.rs
- iot_config/src/route_service.rs
! Depends on https://github.com/helium/proto/pull/288
This doozy introduces several bug fixes in the implementation of the streaming RPCs, retrieving records from the DB and decoding their types, integer size changes in the upstream proto dependency, and devaddr constraints records
- Introduces devaddr constraint bounds checking when attempting to add new devaddr ranges to routers
- Implements the Gateway service's Location rpc
- Implements the Admin service's rpcs and an AuthCache shared between all the services for efficient validation of administrative requests
- Restructures the region_params management rpc underneath the Admin service (formerly under the Gateway service)
- Extends the docker-compose stack to include a mock node-follower service for easier testing
> Config Service bugfixes, Admin API and Gateway Location RPC

- .github/workflows/rust.yml
- iot_config/README.md
Cache the dependencies of the oracles project now that they've grown significantly to get CI build times back down to manageable levels.
This is particularly desirable in the event of a hotfix that needs to be deployed but is held up by a build/release process that takes longer than implementing the actual solution.
> attempting to cache dependencies in the rust build to speed up ci

- file_store/Cargo.toml
When using file-store as a crate the latest versions don't compile. This constrains aws-config to match what is in the cargo.lock
> constrain aws-config + deconstrain aws-sdk-s3

- Cargo.lock
- file_store/Cargo.toml
- file_store/src/file_source.rs
- file_store/src/file_store.rs
- file_store/src/settings.rs
This should enable local testing to read from an AWS bucket and write to a local minio bucket.   The hardcoded credentials will only be used if the "file-store/local" feature is enabled.
> Add ability to hardcode aws creds but only when file-store/local feature is enabled

- iot_config.Dockerfile
- iot_config/src/admin.rs
- iot_config/src/admin_service.rs
- iot_config/src/gateway_service.rs
- iot_config/src/lora_field.rs
- iot_config/src/org.rs
- iot_config/src/org_service.rs
- iot_config/src/route.rs
- iot_config/src/route_service.rs
- iot_config/src/session_key_service.rs
adds additional logging to the iot-config service for error debugging and resolves a bug converting (database persisted) devaddr records, stored in postgres as i32 but otherwise handled as u32 into the u64 DevAddrConstraint struct when retrieved from the database for comparison against requested DevAddrRange records.
the bugfix converts the stored record to the correct unsigned format before casting up to a u64
> bugfix lora field from i32 conversion; more error logs

- iot_config/src/org.rs
This mistaken decode direct to a String type is causing a `Result.unwrap()` panic in a particular handler of the config service attempting to validate updates to the EUI pairs or DevAddr ranges submitted to the config service for routing
> fix erroneous decode route id direct to string

- Cargo.lock
- iot_config/migrations/6_session_key_filters.sql
- iot_config/src/session_key.rs
- iot_config/src/session_key_service.rs
raw binary session keys are proving unwieldy on the routing infrastructure; to manage them better we're converting them to hex-encoded strings on the proto side as well as in the config service, which doesn't really care what format they're in.
this will have the beneficial side effect of making them easier to debug/inspect on if needed
> convert session keys from binary to hex strings

- file_store/src/file_store.rs
- price/src/lib.rs
- price/src/price_tracker.rs
PriceTracker now has a configuration duration that price is allowed to be used.
If now price available in that time range then the PriceTracker task is shutdown and an Err is returned.
> Update PriceTracker to have configurable duration 

- price/src/error.rs
- price/src/lib.rs
- price/src/main.rs
- price/src/price_generator.rs
- price/src/settings.rs
Refactored price service to have 2 modes
1.  If token key is configured, then it will get new price from solana and output on configured cadence. It will also absorb downtimes and use the stale price up to the configured duration
2. If no key is configured, but a default value is, it will output the default price on the configured cadence
3. If no key or default price is configured, the price generator will stop with a value ` Ok(())` for that token.
> Refactor price service and enable stale price lifetime

- file_store/src/cli/info.rs
- file_store/src/entropy_report.rs
- file_store/src/lib.rs
- iot_verifier/migrations/11_files_processed.sql
- iot_verifier/pkg/settings-template.toml
- iot_verifier/src/entropy.rs
- iot_verifier/src/entropy_loader.rs
- iot_verifier/src/loader.rs
- iot_verifier/src/main.rs
- iot_verifier/src/poc_report.rs
- iot_verifier/src/purger.rs
- iot_verifier/src/runner.rs
- iot_verifier/src/settings.rs
Adds the ability to configure the poc loader window via settings, including the window width, max age and poll time.  The start point of the window can be configured by updating the meta db for keys `report` .  Through a combination of the newly added settings and the modification of the meta keys the loaders can be configured to load historic data, looking as far back in time into the S3 bucket as required.
The driver for this is the upcoming switch to solana, whereby the foundation has indicated it may be required to backfill 24hours worth of reports.  
Also includes a refactor of the entropy loader to use continious source. The poc loader cannot move to continuous source as its loading process is more involved.
Also removes the cloning of the full settings struct into various verifier …
> configure loader windows via settings

- iot_verifier/src/reward_share.rs
The reward split between witnesses and beacons has historically been 4:1. On the Helium L1 the current the witnesses are rewarded [0.1892](https://api.helium.io/v1/vars/poc_witnesses_percent) of the epoch rewards and the beaconers are rewarded [0.0473](https://api.helium.io/v1/vars/poc_challengees_percent) of the epoch rewards which corresponds to 4:1. 
```rust
// dc remainer distributed at ration of 4:1 in favour of witnesses
// ie WITNESS_REWARDS_PER_DAY_PERCENT:BEACON_REWARDS_PER_DAY_PERCENT
```
Contrary to the comment the code implements a 3:1 reward split for the dc remainder distribution. This PR rectifies the code to match the Helium L1 behavior as well as the comments in the oracle code.
> Rectify the iot_verifier data transfer remainder to POC reward split

- Cargo.lock
- iot_config/src/admin_service.rs
- iot_config/src/gateway_service.rs
- iot_config/src/region_map.rs
This change is needed to handle gateways requesting region params when they do not have a valid or known default/fallback region set in their local settings.toml files when they make a request to the config service to get the current transmit parameters for their region.
The lookup/response from the config service will be prioritized as follows:
- If the gateway's pubkey/address is found on the current chain with an asserted location, that location will be mapped to a region and from there to region parameters and both will be returned to the gateway
- If the gateway supplies a valid lora region as its fallback and no gateway is found on-chain or the gateway is found to be not asserted the parameters for the fallback region supplied in the request will be returned to the gateway, along …
> handle unknown lora region in config service gateway api

- Cargo.lock
- file_store/src/file_info.rs
- iot_verifier/src/main.rs
- iot_verifier/src/reward_share.rs
- iot_verifier/src/rewarder.rs
- reward_index/migrations/5_add_type_to_index.sql
- reward_index/src/indexer.rs
- reward_index/src/reward_index.rs
- reward_index/src/settings.rs
Depends on proto branch: https://github.com/helium/proto
Refactor to replace GatewayRewardShare with IotRewardShare.  IotRewardShare now supports multiple reward types each with their own data requirements.
Adds output of operational fund rewards
> Refactor to support IotRewardShare and multiple sub reward types.  Add support for operation fund rewards

- iot_config/src/admin_service.rs
- iot_config/src/gateway_service.rs
- iot_config/src/lib.rs
- iot_config/src/org_service.rs
- iot_config/src/route_service.rs
- iot_config/src/session_key_service.rs
- iot_config/src/telemetry.rs
Adds metrics collection to the iot-config service:
- increments a counter for every grpc request received labeled by the service and rpc for grouping queries
- updates counters for the high-volume streaming routing record updates (eui pair, devaddr ranges, and session key filters)
- sets a gauge counting the number of hex cells in the global location-to-region  hextree map
- increments a counter on gateway region params lookup responses, labeled by the default region argument and the region found on lookup
> add iot-config metrics

- iot_verifier/src/reward_share.rs
this changes the yearly emissions for IOT rewards from 60B to 65B and the corresponding test values
> update yearly rewards to 65b

- iot_verifier/src/region_cache.rs
lowering the ttl for the region cache in the iot-verifier to continue to cache region changes (reduce frequent network roundtrips to the config service) while minimizing the impact from region changes which, while happen infrequently, impact 10s-100s of thousands of hotspots at a time when they do occur
> shrink region cache ttl

- file_store/src/iot_packet.rs
The iot packet verifier can output dups, as such using only the fields contained within the verified packet will result in dups being dropped when being inserted into the DB.
This adds a now timestamp component to the packet ID field in the DB to ensure dups get inserted correctly
> ensure packet ids are unique, handle dups

- iot_config/src/route_service.rs
the packet routers have not been able to be upgraded to support the two-way signature verification on the request/response exchange with the config service. to re-enable packet routing temporarily until this upgrade can be rolled out to the HPRs, we need to disable the signature verification on the requests to the stream subscriber
> temporarily disable stream verification for packet routers

- iot_config/src/gateway_service.rs
the router operators requesting location information for gateways are not among the registered infrastructure or oracle keys so this check cannot reasonably be made against keys in the "administrative" store.
> allow router operators to authorize routing location requests

- iot_verifier/src/rewarder.rs
- mobile_verifier/src/verifier.rs
This changes the verifiers to only output the rewards manifest files after the rewards themselves have been committed to s3 and in addition the DB has been purged, thus the manifest file will only show on disk if everything else went as expected.
This avoids the scenario whereby we write out the rewards files including manifest only to have the DB cleanup fail, resulting in the potential for the reward period to not be updated and we end up rerunning the same reward period again
> commit file sinks after rewards db purged

- Cargo.lock
- iot_packet_verifier/src/daemon.rs
- iot_packet_verifier/src/settings.rs
- mobile_packet_verifier/src/daemon.rs
- solana/Cargo.toml
- solana/src/balance_monitor.rs
- solana/src/lib.rs
allow monitoring the lamport balance of oracles that burn lamports in order to process transactions directly on the solana chain. this will allow the oracles to avoid running too low on a balance to maintain operations without advance notice allowing the service maintainer to top up the account
> introducing lamport balance monitor for packet verifiers

- mobile_verifier/README.md
with https://github.com/helium/oracles/pull/492 this message (the related validity field, specifically) is outdated
> fix doc reference

- file_store/src/cli/dump.rs
Summary
----
This adds support for dumping `IotValidPacket` reports.
To run:
```
../target/release/file-store -c file_store_settings.toml dump iot_valid_packet  /path/to/iot_valid_packet.ts.gz
```
> Add support to dump IotValidPacket reports

- Cargo.lock
- iot_config/src/region_map.rs
HexTree still has some minor churn, and this PR updates oracles to the latest v0.3.1 release with the goal of making sure oracles doesn't camp on an old version for too long. This should have no _noticeable_ effect on performance.
> Bump to latest hextree release

- iot_config/migrations/9_delegate_keys.sql
- iot_config/src/gateway_service.rs
- iot_config/src/main.rs
- iot_config/src/org.rs
- iot_config/src/org_service.rs
- iot_config/src/route_service.rs
Two major changes in one here:
- implements a simple cache of delegate keys for all orgs registering LNS's to the config service to restrict the scope of access to the gateway location RPC to only those servers running routers that need it (prevent script kiddies from mapping the network at the expense of the config service and its primary consumer services)
- prepares the delegate keys records for each org for more maintainable record-keeping when org update API is implemented (soon) by moving them out of an array column on the organizations table and into a dedicated child table of the organizations table linked by the OUI
> delegate keys cache and child table

- file_store/src/error.rs
- file_store/src/file_info_poller.rs
- file_store/src/file_sink.rs
- ingest/src/server_iot.rs
- ingest/src/server_mobile.rs
- iot_packet_verifier/src/daemon.rs
- iot_verifier/src/main.rs
- iot_verifier/src/purger.rs
- iot_verifier/src/runner.rs
- mobile_packet_verifier/src/daemon.rs
- mobile_verifier/src/cli/server.rs
- poc_entropy/src/main.rs
- price/src/main.rs
During testing it was discovered 2 issues in the file_store crate that could cause shutdowns to hang.
in file_sink, we learned that calling `sender.send` and the channel is at capacity, it will not error when the receiver is dropped.  Address this by using `sender.send_timeout` and including a shutdown_listener in a `tokio::select`
In file_info_poller, changed to using `sender.try_send` and handling the Full Error by breaking the for loop and waiting for the next interval tick.gg
> Change file_sink and file_info_poller to handle shutdowns better while send data across mpsc channel

- iot_verifier/src/gateway_cache.rs
- iot_verifier/src/gateway_updater.rs
- iot_verifier/src/lib.rs
- iot_verifier/src/loader.rs
- iot_verifier/src/main.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/settings.rs
- iot_verifier/src/tx_scaler.rs
Replaces the gateway info retainer cache and the density scaler's separate streaming of gateway info from config service with a single tokio watch producer.  The producer will periodically ( default 30 mins ) stream all gateways from config service and the resulting gateway map will be consumed by the gateway info cache and the density scalers.
This way the gateway cache and the density scaler are always in sync.  It also eliminates any individual requests to the config service for gateway info.
> Add gateway info producer and consumer data in gateway cache and density scaler

- Cargo.lock
- Cargo.toml
- iot_verifier/Cargo.toml
- iot_verifier/src/hex_density.rs
- iot_verifier/src/poc.rs
- solana/src/balance_monitor.rs
various other projects are switching away from the h3ron c-binding library for h3 index handling to the pure-rust h3o which does more error validation of indexes.
this also necessitated changing of one of the test case index u64 locations which proved to be an invalid cell address as a result of the switch.
> update oracles to replace h3ron with h3o

- iot_verifier/src/rewarder.rs
- mobile_verifier/src/rewarder.rs
New metric that will allow us to make the reward alert more responsive
Plan is to write an alert that will evaluate
`time() - last_over_time(last_rewarded_end_time{}[25h]}` and ensure it is less than configured duration
> Add last_rewarded_end_time guage to mobile and iot verifier

- Cargo.lock
- file_store/src/file_info.rs
- file_store/src/iot_packet.rs
- iot_verifier/src/main.rs
- iot_verifier/src/metrics.rs
- iot_verifier/src/packet_loader.rs
depends on: https://github.com/helium/proto/pull/325
Writes out a paper trail to S3 for verified packets ( outputted by the iot packet verifier ) that are deemed not rewardable.  Currently this would only be in the scenario whereby the gateway does not exist but may in the future extend to additional scenarios ( such as duplicate or free packets )
Also adds metrics to the packet loader
> write out non rewardable packet paper trail to s3

- iot_verifier/migrations/12_bootstrap_disable_data_checks.sql
- iot_verifier/src/rewarder.rs
This adds a check at reward time to verify there is recent data ( POC and DC ).  If there is no data past the reward end time then rewarding is delayed for 5 mins and things are retried.  Also adds an override to skip the check until a point in time
> delay rewards if data not current and retry

- iot_verifier/src/main.rs
- iot_verifier/src/region_cache.rs
- iot_verifier/src/settings.rs
This makes the region cache TTL configurable via settings ( defaults to 30 mins, down from a previous default of 3 hours )
Also adds cache eviction monitoring, which was missing previously
> make region cache ttl configurable. monitor cache for evictions

- Cargo.lock
- Cargo.toml
Awaiting [proto PR](https://github.com/helium/proto/pull/334).
This allows `beacon` and `proto` to come from the same repo, streamlining the testing of proto branches from this repo.
> get beacon module from proto repo

- reward_index/src/indexer.rs
emit a trackable gauge metric whenever the reward indexer processes a reward file to allow alerting when a defined period of time has passed without updating the value as expected
> emit metric gauge whenever reward indexer processes rewards

- iot_config/src/route_service.rs
This fixes a authorization bypass vulnerability which would allow users to update routes of other oui's by specifying the route id of another oui together with their own oui. For example: `{route: {id: <not my route id>, oui: <my oui id>, signer: <my oui public key>, signature: <signature based on my oui's private key>}}` The impact is mimimal as the route id's are uuid's (although mac/time based ones).
> Fixed authorization in RouteService::update

- Cargo.lock
- iot_config/migrations/20230626183323_skip_empty_skf_routes.sql
- iot_config/src/route.rs
per https://github.com/helium/proto/pull/337, the HPRs need to be able to toggle routing or ignoring data packets for routes that have empty session key filters associated with them
> iot-config handle ignore_empty_skf routes

- .github/workflows/rust.yml
Problem to solve: We have hit a limit on packaging deb files on the default public build images.
Solution: Free up additional disk space by removing unneeded packages before we build our debian files
> If we are packaging a release, free up disk space

- iot_config/src/org.rs
restrict payer pubkey updates on iot-config service orgs to administrator authorization only
> only allow authorized admins to update an iot org's payer key

- Cargo.lock
- reward_index/Cargo.toml
- reward_index/src/indexer.rs
The rest of the oracles pipeline treats mobile subscriber_ids as a `&[u8]` or `Vec<u8>` but the foundation reward index database expects the rewardable entity to be a `text` field. According to the nft metadata field for the mobile subscriber rewardable entity the expected serialization is `KeySerialization::B58` so this change aligns the mobile subscriber rewards inserted into the database with the value expected by the on-chain claims program
> ensure mobile subscriber id is properly credited for mobile rewards

- file_store/src/file_info.rs
Summary
----
In preparation for supporting messages coming from spot mapper device, this just adds a `MapperMsg` file type.
> Add MapperMsg filetype

- iot_config/src/gateway_service.rs
- iot_config/src/telemetry.rs
when gateway isn't found on the solana chain (the query succeeds but no record is returned) continue to return the "fallback" response of the region passed in the incoming request and a 0 gain but now in the event of a failure to lookup the requested gateway return a failure to the gateway requesting the region params
> fail region params lookup on db error

- Cargo.lock
- Cargo.toml
- file_store/src/heartbeat.rs
- ingest/src/server_mobile.rs
- mobile_config/migrations/20230708171204_add_pcs_key_role.sql
- mobile_config/src/admin_service.rs
- mobile_config/src/authorization_service.rs
- mobile_config/src/key_cache.rs
- mobile_config/src/lib.rs
- mobile_config_cli/src/client.rs
- mobile_config_cli/src/cmds/mod.rs
- mobile_config_cli/src/lib.rs
- mobile_verifier/src/heartbeats.rs
depends on https://github.com/helium/proto/pull/352
allow the mobile config service to register pcs signing keys so the mobile verifier is able to validate subscriber location and data usage threshold reports submitted by a carrier's propagation calculation service
cleans up duplication of the KeyRole type shared by the mobile config service and its CLI
- temporarily adjusts mobile ingest service and cell heartbeat req messages to allow compilation to succeed with upstream changes already in the proto repo
> allow mobile config service to register pcs signing keys

- mobile_verifier/src/cli/reward_from_db.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/rewarder.rs
In the event there is no rewardable PoC activity from the mobile/cbrs fleet, do a `check_div` on instead of standard division to avoid a divide-by-zero-induced panic and move on with attempting to reward for subscriber location mapping
> allowing for subscriber mapping rewards without radiopoc rewards

- iot_packet_verifier/src/balances.rs
- iot_packet_verifier/src/burner.rs
- iot_packet_verifier/src/daemon.rs
- iot_packet_verifier/src/verifier.rs
- iot_packet_verifier/tests/integration_tests.rs
This should dramatically speed up the iot packet verifier in the pathological case where we've disabled and org, but it continues to hammer the packet verifier. This is basically the worst case; insufficient funds means we must check balance sufficiency every time a packet comes in. We also cache the org disabling so that we don't send outbound requests to the org client every time this happens. 
TODO:
> Cache org client and remove solana cache invalidation for invalids

- iot_verifier/src/reward_share.rs
- mobile_verifier/src/reward_shares.rs
** DO NOT MERGE ***
This updates the iot and mobile verifier to account for the rewards halvening to be applied in August
> rewards halvening

- iot_config/src/route_service.rs
Allows a sanity check from routing infrastructure to re-request information for a specific route without requiring reloading the entire database of routing information.
There can be times where the updating of a routes skfs or euis can be weird. 
An EUI/SKF can be added and removed in an order where HPRs end up with the record, but it no longer exists in the database. Subsequent requests to remove the record from the Config Service will "succeed", but not send any updates to HPRs because no update was made to the database.
Adding HPR permission to `list_skfs` and `get_euis` allows them to do a sanity check of a single route.
> Add stream permission for hpr listing skfs or euis

- mobile_verifier/src/subscriber_location.rs
extends the timeframe from within which subscribers who supplied an initial mapping location event will still be rewarded without having updated with subsequent events.
> extend subscriber location reward 'genesis' period

- Cargo.lock
- denylist/src/denylist.rs
- file_store/src/iot_invalid_poc.rs
- iot_verifier/src/loader.rs
- iot_verifier/src/main.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/purger.rs
- iot_verifier/src/runner.rs
Linked proto pr: https://github.com/helium/proto/pull/362
Moves the denylist check from the loader ( where invalids are dropped ) and into the runner's POC verification list.  The denylist becomes a regular verification alongside the existing POC verifications and results in failed reports getting outputted to S3.
If a beacon is verified `valid` then the verifications are executed for each individual witness which and now includes the denylist check.  The `iot_poc` file outputted to s3 will include metadata enrichment ( location, elevation & gain) for the beacon report and all witnesses (including for both valid and invalid witnesses) and will now include "DENIED" value for the invalid_reason where applicable.
If a beacon is verified `invalid`, all witnesses for that beacon are …
> move denylist check from loader to the runner verification list

- file_store/src/cli/bucket.rs
- file_store/src/cli/info.rs
- file_store/src/file_info.rs
- file_store/src/file_info_poller.rs
- file_store/src/file_sink.rs
- file_store/src/file_store.rs
- file_store/src/lib.rs
- iot_verifier/src/loader.rs
- price/src/price_tracker.rs
Convert the internal FileInfo struct from file-store to have a generic "prefix" instead of an internally defined enum FileType to allow external apps/libraries that use file-store as a dependency to build FileInfos for their own types (when using for searching the S3 records for instance).
This is intended as a minimal refactor; a longer-term solution would be to implement a FileInfo trait that encapsulates the functionality in question and better exposes some common functionality used in the file store cli commands for extension (such as "listing" a collection of files into a stream, filtered by an input type and decoded)
> Make file_store usable outside of oracles

- iot_config/src/route.rs
Because HPRs can send large batches of session key filter changes to reconcile with the central config service and the only operations supported are `add` and `remove` it's possible that changing the value of a session key filter's `max_copies` can result in the total removal of the filter if the request is processed in the current order (add the skf with the new max_copies value and then remove the filter entirely) so this change updates the order of operations to always process removals before processing adds.
This change also enforces that changes to the max_copies field are honored when requested where previously a session key filter record insert would be ignored if the filter/devaddr/route_id triple already existed on the server.
> fixing update order/operations for iot session key filter reconciliation

- file_store/src/file_store.rs
- file_store/src/settings.rs
Support non settings based creation of a filestore. Specifically added to allow the subscriber location service to instantiate a filestore without using a settings file
> add filestore new support

- iot_config/src/route_service.rs
alternative to https://github.com/helium/oracles/pull/597 to expose the route id uuid parsing error to the user when it occurs instead of swallowing it in a less descriptive "auth error".
my basic approach to returning errors to the caller of a public-facing API is to provide as few details as possible for an attacker to exploit and then slowly add more details to make the system usable for the normal good operators just trying to use the system as designed, hence the large default reliance on "not much to see here". i think this is definitely a case where providing the detail of a typoed or invalid UUID format is reasonable detail to return to the user.
> bubble up route uuid parse errors to user

- iot_verifier/src/loader.rs
This change originates from an investigation into a community reported missing witness.  The community member was able to demonstrate a witness being reported to a received beacon but the same witness was not on the selected or unselected lists for the corresponding beacon.
I was able to locate the specific beacon and witness reports from within the ingestor s3 files.
ingestor receive times:
----------------------
beacon: 1691723926989 ( Friday, 11 August 2023 03:18:46.989 )
witness: 1691723930291 ( Friday, 11 August 2023 03:18:50.291 )
ingestor output files:
----------------------
the beacon ended up in a beacon roll up file outputted by the ingestor to s3 with a timestamp of
1691723570113 ( Friday, 11 August 2023 03:12:50.113 )
the witness ended up in a witness roll up file outputted by …
> widen both sides of the witness loader window 

- Cargo.lock
- file_store/src/iot_invalid_poc.rs
- file_store/src/iot_valid_poc.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/purger.rs
- iot_verifier/src/runner.rs
Linked proto PR: https://github.com/helium/proto/pull/366
The proto adds an invalid_details field to invalid witness and  beacon reports and the verified witness report
Enables poc verifications to return additional context on why a report was declared invalid and for those details to be carried through to the protos hitting S3.
Currently the only poc verification check which is populating this field is the denylist check.  If a report is found to be on the denylist `invalid_details` will be set to the tagname of the list in use
A tag name looks like `2023072901`
> enrich denied reports with denylist tagname

- iot_config/src/client/mod.rs
- mobile_config/src/client/authorization_client.rs
- mobile_config/src/client/entity_client.rs
- mobile_config/src/client/gateway_client.rs
- mobile_config/src/client/mod.rs
allow retrying the grpc calls using the mobile config service client to avoid network disruptions or delays on the config service side from crashing the service calling it from the client
> replicate the grpc retriable macro for the mobile config svc

- denylist/src/denylist.rs
- denylist/src/settings.rs
- iot_verifier/src/runner.rs
Linked ops PR: https://github.com/novalabsxyz/ops/pull/775
Replaces a single hardcoded sign key used to verify the signature of denylist updates with N keys defined via settings
> drop hardcoded sign key, replace with support for N keys via settings

- iot_config/src/lib.rs
- iot_config/src/route.rs
- iot_config/src/route_service.rs
This change is to further guard against heavy load on the iot config service preventing route updates from successfully broadcasting those updates out on the HPR stream or from returning a success result to the calling client.
When the service is under load and the broadcast channel it uses to send updates to the connected HPRs is saturated, the route update process will go into a backoff loop until the channel has capacity. While previously done in-line to the grpc handler receiving the update request, this backoff _could_ at times of high load wait long enough for the grpc handler to timeout, either on the client or the server, which causes the request to fail even when the change was successfully persisted to the database.
> broadcast route changes in spawn task

- Cargo.toml
- ingest/src/server_mobile.rs
- iot_config/src/client/mod.rs
- iot_packet_verifier/src/burner.rs
- iot_verifier/src/poc.rs
- mobile_config/src/client/gateway_client.rs
- solana/src/balance_monitor.rs
- task_manager/src/lib.rs
At the stage at the end of `do_witness_verifications` in the iot_verifier poc.rs module where we assign non-zero values to invalid witness metadata we should have validated the witness's on-chain metadata at least (the invalid witness report was invalid for a different reason) so we should assign the witnesses's metadata to its section of the invalid report rather than the beaconer's.
> fix witness metadata on invalid reports

- mobile_verifier/migrations/15_speedtests_one_to_one.sql
- mobile_verifier/src/cli/reward_from_db.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/heartbeats.rs
- mobile_verifier/src/lib.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/speedtests.rs
- mobile_verifier/src/speedtests_average.rs
- mobile_verifier/src/subscriber_location.rs
Refactor the speedtests to prevent scenario whereby the rewards can use reports from after the epoch end.  To accommodate this I had to explode the speedtests reports in the DB from 1 row containing an array of up to 6 reports out into 1 row per report.
At the same time i have split the averaging code out from the speedtest module into its own module for better readability and maintainability.
> refactor speedtests handling, ensure rewards only include tests up until epoch end

- Cargo.lock
- Cargo.toml
- denylist/src/denylist.rs
- iot_verifier/src/poc.rs
This change adds support for denying of hotspot-hotspot edges when the denylist system considers an edge invalid because of one of its classifiers but is unable to assign blame to a specific hotspot. This allows the denylist to deny earnings for bad edges without accidentally denying hotspots that are simply adjacent or enmeshed in a cluster of badly behaving hotspots, or anoymous radio repeater devices.
Hotspot edges are not directional, so A->B is considered the same as B->A. To accomplish this, the hotspot keys are always lexiographically ordered when constructing the hash to check the denylist.
> Add support for denied edges in the denylist

- file_store/src/error.rs
- file_store/src/iot_packet.rs
- iot_packet_verifier/src/verifier.rs
- iot_packet_verifier/tests/integration_tests.rs
Make lora join packets free for the iot network by having the iot packet verifier ignore them when determining if packets have been paid for. Join packets are skipped over when reviewing packet reports so they are not burned against the sending OUI's wallet and are likewise not marked as "invalid"
> iot packet verifier ignores join packets

- file_store/src/file_store.rs
If you're wondering why downloading files will randomly give you an XML file, this is why
> Fix S3 from guessing the content type, which it will occasionally guess as XML

- Cargo.lock
Bump xor-generator to 0.6.0 just to keep up to date. Filters are still compatible
> Bump xorf generator

- Cargo.lock
- file_store/src/iot_invalid_poc.rs
- file_store/src/iot_valid_poc.rs
- iot_config/Cargo.toml
- iot_config/src/admin_service.rs
- iot_config/src/gateway_service.rs
- iot_config/src/main.rs
- iot_config/src/org.rs
- iot_config/src/org_service.rs
- iot_config/src/route_service.rs
Applies taskmanager control the the mobile config oracle
Removed some internal shutdown listeners on some of the services.  Impact of these removals needs considered further and if required then will need to implement and alternative pattern
> taskman up iot config

- file_store/src/error.rs
In order to implement the streaming file info poller the trait bounds require the implementer to define an impl of the `MsgDecode` trait which itself requires the `TryFrom` of the source to the destination type but also explicitly defines the TryFrom associated Error type as being file_store::Error. This allows passing errors from external instances of the MsgDecode trait without having to force them into one of the limited pre-defined list of FileStore error variants.
> Allow fallible errors from external implementations of file source

- iot_verifier/src/poc.rs
- iot_verifier/src/runner.rs
- iot_verifier/src/settings.rs
Assume beacon interval is defined in settings as seconds
Convert beacon interval from seconds to Duration via settings accessor
Use beacon interval as duration throughout iot verifier
> assume beacon interval defined in seconds

- iot_packet_verifier/src/burner.rs
- iot_packet_verifier/src/daemon.rs
This also means we reduce the amount of time we hold the balance lock, thus speeding up the iot packet verifier throughput
> Remove unnecessary payer balance lookup in burn

- Cargo.lock
- Cargo.toml
- db_store/Cargo.toml
- denylist/Cargo.toml
- file_store/src/traits/msg_timestamp.rs
- iot_verifier/Cargo.toml
- mobile_config_cli/Cargo.toml
- mobile_verifier/src/cli/reward_from_db.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/speedtests_average.rs
- reward_index/Cargo.toml
- solana/Cargo.toml
- task_manager/Cargo.toml
This addresses <https://github.com/helium/oracles/issues/670> as well as performs several minor and patch updates to the various dependencies that aren't blocked on various crypto locks (based on compatibility with Solana dependencies) and dependencies that are blocked on upgrading sqlx from the internal patch (also blocked on crypto dependency updates per the above I believe).
Noteworthy dependency collections that this cannot currently addressed are:
- Anything related to solana (which includes helium-crypto)
- sqlx (low-level dependencies that are blocked on conflicts with some of the above crypto deps)
- AWS sdk (low-level dependencies that are blocked on conflicts with some of the above crypto deps, i.e. p256, ecdsa, etc)
Also of note, this does _not_ roll the `http` forward into the …
> update as many dependencies as we can

- Cargo.lock
- Cargo.toml
- file_store/src/traits/msg_verify.rs
- mobile_config/Cargo.toml
- mobile_config/src/gateway_info.rs
- mobile_config/src/gateway_service.rs
- mobile_config/src/key_cache.rs
in-between rpc for getting a batch of gateways' info in a single request, streamed back to the caller without having to request _all_ gateways' info
> mobile config gateway grpc service supports batches of info

- mobile_config/src/gateway_info.rs
incorrectly decoding the asserted location from string to u64 with the incorrect radix
> correctly hex decode asserted location

- mobile_config.Dockerfile
- mobile_config/src/client/gateway_client.rs
- mobile_config/src/client/mod.rs
- mobile_config/src/gateway_info.rs
- mobile_config/src/gateway_service.rs
- mobile_config_cli/src/client.rs
- mobile_config_cli/src/cmds/gateway.rs
- mobile_config_cli/src/cmds/mod.rs
- mobile_config_cli/src/main.rs
Properly query for mobile hotspot batches from the database (correct the construction of the `vec<publickey` that's passed to the metadata db query as well as type cast the query parameter to hint at the format of the results: `bytea[]`.
Also converts the `From<GatewayInfoProto> for GatewayInfo` to `TryFrom` to error if/when the parsing of the hex address errors.
> mobile config gateway decoding fixes

- iot_config/src/route.rs
In a scenario such as:
1. Add Route
2. Add SKF
3. Remove Route
If a stream is created requesting updates since before the first action, it will receive:
1. Remove Route
2. Add SKF
With these changes, the route removal will be streamed, allowing HPR to clean up related configuration, and the Adds afterwards will be ignored.
> do not stream updates for routes that have been deleted

- mobile_config_cli/src/cmds/gateway.rs
- mobile_config_cli/src/cmds/mod.rs
Since this is a clap-based CLI, the way a vec of input arguments works would be `mobile-cli gateway info-batch --hotspot <key1> --hotspot <key2> ...` where the flag name is just repeated as many times as necessary to supply all the elements of the input vec. naming this batch flag `hotspot` instead of `hotspots` makes more sense in the way the CLI is used
> make mobile cli input more semantic

- Cargo.lock
- Cargo.toml
- file_store/src/cli/dump.rs
- file_store/src/traits/msg_verify.rs
- iot_verifier/src/reward_share.rs
- iot_verifier/src/runner.rs
- mobile_config/migrations/5_carrier_service.sql
- mobile_config/src/carrier_service.rs
- mobile_config/src/client/carrier_service_client.rs
- mobile_config/src/client/mod.rs
- mobile_config/src/client/settings.rs
- mobile_config/src/lib.rs
- mobile_config/src/main.rs
- mobile_config_cli/src/client.rs
- mobile_verifier/src/cli/server.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/speedtests.rs
- reward_index/migrations/7_add_service_provider_reward_type.sql
- reward_index/src/indexer.rs
related hip: https://github.com/helium/HIP/blob/main/0087-proportional-service-provider-rewards.md
related proto pr: https://github.com/helium/proto/pull/377
> add service provider rewards support

- mobile_verifier/src/heartbeats/cbrs.rs
Removes the filtering of CBRS heartbeats to discard a HB when we had already seen a HB for a given hour.  This results in all cbrs HBs being processed and validated and the results being outputted to S3.
The filtering was added as a temp measure due to slow processing on mainnet.  That slowness was properly addressed by a refactor of DB usage as part of #685.  
Local performance testing resulted the following average times for the processing of each cbrs HB ingest file:
With filtering:  14 seconds
Without filtering: 24 seconds
24 seconds without filtering is an acceptable time and results in the benefit of all HBs being processed
> process all cbrs heartbeats, remove filtering

- Cargo.lock
- mobile_config/src/client/carrier_service_client.rs
- mobile_config/src/client/mod.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/tests/rewarder_sp_rewards.rs
- reward_index/src/indexer.rs
This makes use of centralised from_str and to_string impls added to the proto lib here https://github.com/helium/proto/pull/386 and removes the temp added local functions.
There is the option of updating mobile_config server  to return the Service Provider enum value but I am not convinced that is a good approach as it enforces a specific enum to what could be argued is a generic API (key_to_rewardable_entity) which translates a given key to a rewardable entity.  Baking in the assumption that a rewardable entity will always be a service provider enum would be a mistake.  
The other option is to drop the generic API (naming & usage ) and make it specific to returning a service provider entity key.  I ended up taking this approach but limited it to the mobile config client.  The server …
> use service provider proto string impls

- iot_config/src/route.rs
- iot_config/tests/route_service.rs
Allow reactivating route sub-records by unsetting the `deleted` boolean flag if the record has been deleted within the tombstone retention period but needs to be reactivated (by re-adding the record)
> allow reactivating eui pairs, devaddr ranges and skfs

- iot_config/tests/route_service.rs
* allow reactivating eui pairs, devaddr ranges and skfs
* fix update skf query
* test reactivation of lns route records
> allow reactivating eui pairs, devaddr ranges and skfs (#713)

- mobile_verifier/src/cli/server.rs
- mobile_verifier/src/geofence.rs
- mobile_verifier/src/settings.rs
I thought about other programmatic ways to do this that shared the same geofence objects but that seemed more complicated than necessary
> Separate out cbrs and wifi geofence regions

- Cargo.lock
- iot_verifier/migrations/14_last_witness.sql
- iot_verifier/src/last_witness.rs
- iot_verifier/src/lib.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/poc_report.rs
- iot_verifier/src/runner.rs
- iot_verifier/src/tx_scaler.rs
- iot_verifier/tests/common/mod.rs
- iot_verifier/tests/runner_tests.rs
proto pr: https://github.com/helium/proto/pull/388
This adds a reciprocity or bidirectional  validation to POC validations in order to satisfy https://github.com/helium/HIP/blob/main/0106-hotspot-bidirectional-coverage-requirement.md
The flow is as follows:
1.  Run regular validations on POC ( per beacon and any associated witnesses )
2.  After regular validations update DB to track the 'last beacon' and 'last witness' timestamps per relevant gateway 
- If regular validations declared the  beacon valid then record last valid beacon timestamp ( 1 update per beacon)
- If regular validations declared the  witness valid then record last valid witness timestamp ( 1 update per witness )
3.  After updating the DB then run the reciprocity check:
- For each previously declared valid witness, …
> reciprocity checks

- mobile_verifier/src/rewarder.rs
- mobile_verifier/tests/rewarder_poc_dc.rs
This addresses the issue in mobile rewards where we calculate poc and dc rewards independently and potentially write out unallocated amounts for each.
With these changes any unallocated DC amount is now carried over into the poc pool.  We then only write out a single unallocated reward for POC.
> carry unallocated dc to poc pool, dont write unallocated dc proto

- iot_verifier/src/poc.rs
- iot_verifier/tests/runner_tests.rs
This extends the beacon reciprocity check to cover the scenario whereby a gateway is submitting beacons and there are no corresponding witnesses for that beacon.  This could be due to the beacon being a lone wolf or it has a hardware fault whereby it cannot actually transmit the beacon but continues to submit reports to the oracle.
In these cases the beacon will now fail the reciprocity as it requires at least one associated witness report
> beacon fail reciprocity check if no witnesses

- iot_verifier/src/poc.rs
- iot_verifier/tests/runner_tests.rs
This addresses the current scenario whereby a gateway which is submitting beacon reports but does not have any witnesses ( be that due to being a lone wolf or it has faulty hardware preventing it being able to transmit) from being able to receive witnessing rewards.
Prior to this change the gateways beacon reports would pass regular verifications and then subsequently fail reciprocity as the beacon reciprocity check would return invalid as the beacon had no witnesses. As the last_beacon timestamp is updated should the beacon pass regular verifications it resulted in a gap whereby the gateway was able to witness and earn rewards for those witnesses, despite it never having a successful beacon ( ie passing both regular verifications + reciprocity ).
With this change the rule that the last …
> fail beacons with no witnesses

- iot_verifier/src/last_beacon.rs
- iot_verifier/src/last_witness.rs
- iot_verifier/src/lib.rs
- iot_verifier/src/main.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/runner.rs
- iot_verifier/src/tx_scaler.rs
- iot_verifier/src/witness_updater.rs
- iot_verifier/tests/common/mod.rs
- iot_verifier/tests/runner_tests.rs
This addresses DB deadlock errors encountered as a result of the recent reciprocity check implementation.   
The core of the deadlock issue is as follows:
1. we spawn up to 100 concurrent POCs
2. each poc process attempts to bulk update the last witness table to record the timestamp of each gateway's last witness event
3. if across multiple POCs there are one or more reports from the same gateway, then it is possible for those concurrent processes to attempt to update the same record of the last witness table at the same time, thus triggering the deadlock
NOTE: the deadlock did not result in any loss of data or a drop in POCs being processed. Any POC which hit the deadlock would be re-queued and retried next tick ( up to a max of 10 times )
The fix is to serialize all writes to the last …
> serialize last witness DB writes

- file_store/src/error.rs
Add ExternalError variant to file_store::error::Error. It will simplify external implementation of MsgDecode, StateRecord and State traits.
> add ExternalError variant to file_store::error::Error

- iot_verifier/src/poc.rs
- iot_verifier/src/runner.rs
- iot_verifier/tests/runner_tests.rs
Refactor the reciprocity checks.  As part of this refactor, some furniture has been moved around and some obvious poor code updated in order to make the functional changes clearer to follow.  There remains a lot of opportunity for additional refactor but it goes beyond the scope of this PR and including any additional refactor makes it difficult to determine the scope of actual functional changes.   
NOTE: regular verifications = all report verifications excluding reciprocity checks
The reciprocity checks have been moved out of the `poc` beacon and witness verification flows and into the `runner` where they are applied post regular verifications of the beacon and witnesses .  Reciprocity checks are applied to the witnesses only if the beacon itself is valid ( ie all regular verifications …
> apply reciprocity checks post beacon & witness verification

- Cargo.lock
- Cargo.toml
- mobile_verifier/src/heartbeats/mod.rs
Had feedback from community that multiple radios have same signal power and seniority timestamp.  Upon investigation the issue that we only output the seniority timestamp in seconds and that the seniority timestamps in this example are not equals but have only millisecond difference.  
This PR deprecates the current second on timestamp and adds a new seniority timestamp in milliseconds to the seniority update protobuf.
Proto PR: https://github.com/helium/proto/pull/396
> Update seniority update to include new field that is seniority timestamp in milliseconds

- iot_verifier/migrations/15_last_beacon_reciprocity.sql
- iot_verifier/src/last_beacon.rs
- iot_verifier/src/last_beacon_reciprocity.rs
- iot_verifier/src/lib.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/runner.rs
- iot_verifier/tests/common/mod.rs
- iot_verifier/tests/runner_tests.rs
Further tweaks associated with hip106 side effects.
With this change we now track the time a gateway last submitted a beacon separately from the beacon reciprocity timestamp.  Previously we tracked a single timestamp for both purposes.
The last beacon timestamp is used to enforce the beacon schedule and is updated post verification of a received beacon.  The timestamp is updated whether the beacon is valid or invalid and thus a gateway can only submit one beacon per beaconing window irrespective of the beacon being valid/invalid or rewardable/non rewardable.
The beacon reciprocity timestamp is used to enforce beacon reciprocity.  This timestamp is updated post verification and only if the beacon is rendered valid and has at least one witness.
> track last beacon ts for schedule and recip separately. ensure only one beacon attempt per beaconing window

- boost_manager/src/main.rs
- file_store/src/file_sink.rs
- ingest/src/server_iot.rs
- ingest/src/server_mobile.rs
- iot_packet_verifier/src/daemon.rs
- iot_verifier/src/main.rs
- mobile_packet_verifier/src/daemon.rs
- mobile_verifier/src/cli/server.rs
- poc_entropy/src/main.rs
- price/src/main.rs
`FileSink.file_upload` was added as an alternative `FileSink.deposits`. 
They behave in a mutually exclusive manner, and no production code was constructing a `FileSink` without providing a `FileUpload`. (There was one test that made a FileSink without a destination channel).
This PR removes the ability to use `FileSinkBuilder.deposits` and the corresponding `FileSink.deposits`;
and requires a `FileUpload` when constructing a `FileSinkBuilder`.
> Refactor FileSinkBuilder

- Cargo.toml
Metrics dependency announced v0.22 with breaking changes that aren't supported by `oracles`
https://github.com/metrics-rs/metrics/blob/a143ef60b5354770fb292d29acc1f7bdef2c4aed/metrics/RELEASES.md#0220---2023-12-24
When I use the `file_store` as a dependency it doesn't compile until I add a patch fix to my project
```
[patch.crates-io]
metrics = { git = "https://github.com/metrics-rs/metrics", tag = "metrics-v0.21.1"}
```
Use `metrics = 0.21` to let use `oracles` crates as a dependency without hack
> Fix compilation error for projects that use oracles as dependency 

- mobile_verifier/src/radio_threshold.rs
Bug was introduced when fixing the db deadlock issue.
Code is commiting the wrong file sink at the end of processing the invalid radio threshold files
> Commit the verifier invalid sink at the end of processing invalid rado threshold files

- Cargo.lock
- ingest/tests/iot_ingest.rs
- iot_config/tests/route_service.rs
- mobile_config/Cargo.toml
- mobile_config/src/gateway_service.rs
- mobile_config/src/key_cache.rs
- mobile_config/src/main.rs
- mobile_config/tests/gateway_service.rs
Update the Mobile Config Gateway Service to allow gateways to request information about themselves.
ORA-350
> Gateway service info perms

- Cargo.lock
- Cargo.toml
- mobile_verifier/migrations/32_landtype.sql
- mobile_verifier/src/boosting_oracles/assignment.rs
- mobile_verifier/src/boosting_oracles/mod.rs
- mobile_verifier/src/cli/mod.rs
- mobile_verifier/src/cli/server.rs
- mobile_verifier/src/cli/verify_disktree.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/geofence.rs
- mobile_verifier/src/main.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/settings.rs
- mobile_verifier/tests/boosting_oracles.rs
- mobile_verifier/tests/common/mod.rs
- mobile_verifier/tests/hex_boosting.rs
- mobile_verifier/tests/modeled_coverage.rs
- mobile_verifier/tests/rewarder_poc_dc.rs
https://github.com/helium/proto/pull/398
Add Landtype to Hex Boosting.
---
`Assignments` are never considered individually, nor should they be. This type packs them together, allowing any code that requires specific use of `Assignment` order to attach itself here.
It also allows `boostring_oracles/mod.rs` to reduce it's reliance on traits. There is now a single exported `BoostedHexAssignments` that allows for getting a `HexAssignments`.
---
With only exporting a single trait from `boosting_oracles/mod.rs`, the `CoverageDaemon` now takes the concrete struct `HexBoostData` with no generic arguments.
Downstream from the `CoverageDaemon`, functions will take `impl BoostedHexAssignments` so they can be used in tests.
---
A CLI command was added to `mobile-verifier`.
It verifies a `.h3tree` …
> Landtype Boosting

- mobile_verifier/src/cli/server.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/heartbeats/cbrs.rs
- mobile_verifier/src/heartbeats/wifi.rs
- mobile_verifier/src/radio_threshold.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/settings.rs
- mobile_verifier/src/speedtests.rs
- mobile_verifier/src/subscriber_location.rs
Moved as much startup code as possible into each daemon.  Anything shared is still started in main run function for mobile verifier.
Goal is to make initialization code for each daemon separate and easier to understand startup/shutdown order.
> Refactor mobile_verifier main run function

- Cargo.lock
- boost_manager/src/activator.rs
- boost_manager/tests/activator_tests.rs
- boost_manager/tests/watcher_tests.rs
- mobile_config/src/boosted_hex_info.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/tests/hex_boosting.rs
- mobile_verifier/tests/modeled_coverage.rs
This is something that I was planning on doing as part of HIP-109 changes I was going to be making. 
So I thought I'd push it early to make it easier to review.
---
Got some advice from Jay to only use a `h3o::CellIndex` when you need to
convert to/from a LatLng. So we went with `hextree::Cell` for the type.
`hextree::Cell` is a loose wrapper around a u64. Parsing the value as
early as possible tightens the gaurantee that we can make valid types
that need use `Cell`s.
It is also an attempt to remove discrepancies where some types carry a
`i64` hex straight from a database, and other types carry a `u64` that
were converted out of a database, even though they're goal is the same.
(see previous commit where `#[sqlx(try_from = "i64")]` was enabled by
the update to hextree).
> Refactor: Hex location use `hextree::Cell` type

- iot_verifier/src/last_beacon_reciprocity.rs
- iot_verifier/src/tx_scaler.rs
Fix for issue https://github.com/helium/oracles/issues/793
This changes the hex density scaler to use the last_beacon_recip table as its source data rather than the `last_beacon` table.  As per #784 the last_beacon_recip table is updated only when a beacon is valid whereas the last_beacon table is updated upon receipt of the last beacon whether than beacon is valid or invalid.  
As such since #784 the hex density scaler has been using incorrect data
> use beacon recip table rather than last beacon table for active beaconing gateways

- file_store/src/file_info_poller.rs
- file_store/src/file_source.rs
- file_store/src/file_store.rs
To support reading AVRO files for the CDR project, added a `FileInfoPollerParser` trait responsible for parsing the file from s3 into a `Vec<T>`.  A implementation that supports Protobufs will be defaulted if `continuous_source` is used to construct the `FileInfoPoller`
> Add FileInfoPollerParser trait with implementation for Protos

- mobile_verifier/src/boosting_oracles/mod.rs
- mobile_verifier/src/cli/server.rs
This PR bundles the USA geofence into the urbanization boosting oracle, thus having no more need for the USA geofence
> Bundle usa geofence into urbanization

- boost_manager/tests/common/mod.rs
- boost_manager/tests/watcher_tests.rs
- mobile_verifier/tests/common/mod.rs
- mobile_verifier/tests/hex_boosting.rs
- mobile_verifier/tests/rewarder_poc_dc.rs
- mobile_verifier/tests/rewarder_sp_rewards.rs
It seems like this version of Rust does not like to have `struct` and `impl` in different files.
> Fix clippy

- ingest/src/server_iot.rs
- ingest/src/server_mobile.rs
- ingest/src/settings.rs
- ingest/tests/iot_ingest.rs
- iot_config/src/main.rs
- iot_config/src/settings.rs
- iot_config/tests/route_service.rs
- metrics/src/lib.rs
- metrics/src/settings.rs
- mobile_config/src/main.rs
- mobile_config/src/settings.rs
- `SocketAddr` can be parsed directly from a config file. This moves potential errors even earlier in the bootup process.
- During tests, get an assigned open port from the OS. This removes the small chance you get a conflicting port when running tests locally.
> Socket Addrs

- Cargo.lock
- boost_manager/src/settings.rs
- denylist/src/settings.rs
- ingest/src/settings.rs
- iot_config/src/client/settings.rs
- iot_config/src/settings.rs
- iot_packet_verifier/src/settings.rs
- iot_verifier/src/settings.rs
- mobile_config/Cargo.toml
- mobile_config/src/client/authorization_client.rs
- mobile_config/src/client/carrier_service_client.rs
- mobile_config/src/client/entity_client.rs
- mobile_config/src/client/gateway_client.rs
- mobile_config/src/client/settings.rs
- mobile_config/src/settings.rs
- poc_entropy/src/settings.rs
- price/src/settings.rs
- `humantime_serde` the missed mobile-config client settings
- default functions for serde do not need to be exported
- file_store default region is a special case because it's used
- remove some unused settings
> settings shenans

- .github/workflows/CI.yml
- README.md
Using `protoc action` avoid downloading `protoc` with `apt-get` and saves on average 30s on build time.
> Use protoc action

- Cargo.lock
- Cargo.toml
- coverage_map/Cargo.toml
- coverage_map/src/indoor.rs
- coverage_map/src/lib.rs
- coverage_map/src/outdoor.rs
- mobile_config/Cargo.toml
- mobile_config/src/boosted_hex_info.rs
- `CoverageMapBuilder`: A data structure for keeping track of the current rank of all of the radios providing coverage to a given set of hexes. This data structure does not allow you to map radios to their ranked hex coverage, but allows you to build the `CoverageMap` data structure which does. Additionally, you can create a "submap" from a `CoverageMapBuilder` and a collection of `CoverageObject`s, which allows for inserting ranking only those hexes which are relevant to the set of `CoverageObject`s provided.
- `CoverageMap`: A data structure that maps hotspots to all of their ranked hex coverage.
This crate is basically complete, but the following work remains:
> Add `coverage_map` crate to provide `CoverageMapBuilder` and `CoverageMap` data structures

- Cargo.lock
- coverage_map/Cargo.toml
- coverage_map/src/indoor.rs
- coverage_map/src/lib.rs
- coverage_map/src/outdoor.rs
In an effort to keep this crate simple and the deps small, refactored to treat the hotspot_key as just a bag of bytes rather than a PublicKeyBinary.
> Change coverage map to treat hotspot_key as bytes rather than a PublicKeyBinary

- mobile_verifier/src/boosting_oracles/data_sets.rs
This PR abstracts out the data set processing part of the `DataSetDownloader` into a separate trait. 
There are two implementers, `FileSinkClient` and `NopDataSetProcessor`. 
This is so that the `DataSetDownloader` can be used without processing the data. 
The implementer of this trait being `FileSinkClient` is because you would only want to supply a file sink if you are processing the data.
> Abstract data set processing to a trait

- Cargo.lock
- coverage_point_calculator/Cargo.toml
- coverage_point_calculator/src/hexes.rs
- coverage_point_calculator/src/lib.rs
- coverage_point_calculator/src/location.rs
- coverage_point_calculator/src/speedtest.rs
- coverage_point_calculator/tests/coverage_point_calculator.rs
Many changes to the rewards algorithm are contained in and across many HIPs. The blog post [MOBILE Proof of Coverage][mobile-poc-blog] contains a more thorough explanation of many of them. It is not exhaustive, but a great place to start.
Please comment if...
- You think something can be named more appropriately
- You have tests you'd like to see
- You think something is important and we should try to make it less hidden
- You can provide additional context to some part of how scores are calculated
- Saying hi
- You think more explanation could be provided to someone perusing the code
- You feel like
```rs
type RadioId = (PublicKeyBinary, Some(String));
pub async fn coverage_points(
&mut self,
radio_id: &RadioId,
) -> anyhow::Result<coverage_point_calculator::CoveragePoints> {
let pubkey …
```
> Mobile Coverage points calculator

- coverage_point_calculator/src/speedtest.rs
- coverage_point_calculator/tests/coverage_point_calculator.rs
Add a mock speedtest constructor. This is so that the mobile rewards estimator can easily construct a collection of speedtests that are guaranteed to be assigned `SpeedtestTier::Good` when averaged. 
I'm open to better ways of doing this, this just seemed like the easiest way
> Add mock speedtest constructor

- .github/workflows/CI.yml
- coverage_point_calculator/src/lib.rs
We forgot to include new crates in the CI yaml.
`coverage-map` https://github.com/helium/oracles/pull/819
`coverage-point-calculator` https://github.com/helium/oracles/pull/824
> Add `coverage-map` and `coverage-point-calculator` to CI

- Cargo.lock
- Cargo.toml
- price/Cargo.toml
- price/src/price_generator.rs
- price/src/settings.rs
Current Pyth feeds are being deprecated and we have to move to using new sponsored feeds.
Sponsored feeds are not backwards compatible.
> Update to use pyth sponsored feeds

- iot_config/src/route_service.rs
- iot_config/tests/route_service.rs
Needed permission change for https://github.com/helium/helium-packet-router/pull/303.
There is enough configuration now that it no longer makes sense to dump everything and start over if there is a discrepancy between Packet-Routers and their configuration information. 
They already have access to update euis, skfs, and devaddr ranges for individual routes.
But there was no way to get a current list of routes, or update a route individually if an HPR thought it was stale.
These perms allow for that.
> HPR route service list get

- .github/workflows/CI.yml
Sometimes (more often than we want) we hit the rate limit to download the protoc action (see https://github.com/helium/oracles/actions/runs/9846105487/job/27183162620?pr=836). By logging in we get a higher rate limit.
> Avoid rate limit for protoc github action install

- coverage_point_calculator/src/hexes.rs
- coverage_point_calculator/src/lib.rs
- coverage_point_calculator/tests/coverage_point_calculator.rs
- mobile_verifier/src/cli/reward_from_db.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/tests/integrations/common/mod.rs
- mobile_verifier/tests/integrations/hex_boosting.rs
Reference: [HIP-122](https://github.com/helium/HIP/blob/main/0122-amend-service-provider-hex-boosting.md)
Data Transfer rewards used to be calculated to fit within the `MAX_DATA_TRANSFER_REWARDS_PERCENT` from the total scheduled tokens for an epoch. This has been moved to the construction of `DataTransferAndPocAllocatedRewardBuckets` so boosted poc rewards can be carved out of the poc allocation as soon as possible. 
After Data Transfer has been rewarded, the unallocated amount is rolled into the normal POC bucket with `reward_shares.handle_unallocated_data_transfer(dc_unallocated_amount);`.
Unallocated Data Transfer rewards are allowed to increase the POC rewards, **but not service provider boosted rewards**.
(In the case where boosted rewards do not exceed 10%, nothing extra needs to be …
> HIP-122 restrict boosting from poc bucket

- coverage_point_calculator/src/hexes.rs
- file_store/src/reward_manifest.rs
The `modeled` field in `HexPoints` is currently private. However, it is useful for upstream crates, so let's make it public.
This PR also fixes some naming in our file store struct for the mobile reward manifest
> Make `modeled` field in `HexPoints` public

- Cargo.toml
- iot_config/Cargo.toml
- iot_verifier/Cargo.toml
- mobile_config/Cargo.toml
- mobile_verifier/Cargo.toml
The `oracles` codebase is unable to compile with `prost = 0.13` version which breaks the compilation process for projects that use `oracles` crates.
Solution: using explicitly `prost = 0.12` 
Make it possible to use `oracles` with  `helium-crypto-rs` but without forced sqlx dependency
> Makes oracles more friendly to use as library

- iot_verifier/src/reward_share.rs
- iot_verifier/tests/integrations/rewarder_operations.rs
- iot_verifier/tests/integrations/rewarder_oracles.rs
- iot_verifier/tests/integrations/rewarder_poc_dc.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/tests/integrations/hex_boosting.rs
- mobile_verifier/tests/integrations/rewarder_mappers.rs
- mobile_verifier/tests/integrations/rewarder_oracles.rs
- mobile_verifier/tests/integrations/rewarder_poc_dc.rs
- mobile_verifier/tests/integrations/rewarder_sp_rewards.rs
On Aug. 1 2024, rewards need to be calculated based on 365 days a year, not 366.
> Remove leap year when calculating rewards - Deploy on Aug. 1st, 2024

- db_store/src/iam_auth_pool.rs
- db_store/src/settings.rs
This PR enables certificate authority verification for our SQL connections
> Add verify ca and root cert path to settings

- .github/workflows/CI.yml
- file_store/src/file_info_poller.rs
- file_store/src/file_source.rs
- mobile_verifier/src/sp_boosted_rewards_bans.rs
A `FileInfoPollerServer` keeps track of processed files in a db table. To keep from growing forever, this table is cleaned when   a `FileInfoPollerServer` is started, and every 12 hours afterwards, to the most recent 100 processed files. For most cases, this is well and good.
To fetch files for processing, the timestamp of the latest processed file and an `offset` Duration is used to determine how far back to look.
A burst of files arrived on devnet exceeding the 100 row limit. And they were processed. It was good.
For sake of this tale, let's say 150 files arrived in 10 minutes. And the `offset` provided was 1 hour.
Later, the cleanup job came around (or when the service was restarted) and removed the 50 that were over the limit. 
The next time the `FileInfoPollerServer` was asked for …
> `FileInfoPollerServer` lookback exceeds limit leads to reprocessing files

- boost_manager/src/main.rs
- file_store/src/file_sink.rs
- file_store/src/traits/file_sink_write.rs
- file_store/src/traits/mod.rs
- ingest/src/server_iot.rs
- ingest/src/server_mobile.rs
- iot_packet_verifier/src/daemon.rs
- iot_verifier/src/main.rs
- mobile_packet_verifier/src/daemon.rs
- mobile_verifier/src/boosting_oracles/data_sets.rs
- mobile_verifier/src/cli/server.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/radio_threshold.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/sp_boosted_rewards_bans.rs
- mobile_verifier/src/speedtests.rs
- mobile_verifier/src/subscriber_location.rs
- mobile_verifier/src/subscriber_verified_mapping_event.rs
- poc_entropy/src/main.rs
- price/src/main.rs
In a previous update to [`file_store`](https://github.com/helium/oracles/pull/849) I had a misunderstanding of the `auto_commit` and `roll_time` settings. I thought `auto_commit=true` would cause a file sink to commit itself on every write, which would mean the settings were in opposition of each other. 
**Then arose such a clatter** (_Oh the folly of my ways_)
File Sinks where the settings had previously set `auto_commit=true` and `roll_time=any_duration` were converted to only the `roll_time` being set and `auto_commit=false`. 
These file sinks were expecting `max_size` or `roll_time` to be the driver of when a file was uploaded to s3. With `auto_commit=false`, the file sink was rolling the file into temporary storage, waiting for a `.commit()` that would never come. 
____
Add …
> Fix `roll_time` and `auto_commit` settings for `FileSink`

- custom_tracing/src/settings.rs
By default, file named `tracing.cfg` should be created where executable is started. This can be changed via config:
```
[custom_tracing]
tracing_cfg_file = "/tmp/tracing.cfg"
```
Notes: 
- File can be created after.
- Deletion of the file will remove custom filter (tested using `rm file` but for some reason when doing in editor it does something weird)
- Empty the file will remove the custom filter.
> Fix default for custom tracing

- Cargo.lock
- Cargo.toml
- file_store/src/cli/dump_mobile_rewards.rs
- file_store/src/file_info.rs
- file_store/src/lib.rs
- file_store/src/promotion_reward.rs
- file_store/src/traits/file_sink_write.rs
- file_store/src/traits/msg_verify.rs
- ingest/src/server_mobile.rs
- ingest/tests/common/mod.rs
- mobile_verifier/src/rewarder.rs
- promotion_fund/Cargo.toml
- promotion_fund/README.md
- promotion_fund/pkg/settings-template.toml
- promotion_fund/src/daemon.rs
- promotion_fund/src/lib.rs
- promotion_fund/src/main.rs
- promotion_fund/src/settings.rs
- reward_index/migrations/11_add_mobile_promotion_reward_type.sql
- reward_index/src/indexer.rs
- solana/src/carrier.rs
- solana/src/lib.rs
**Wait What?** To keep the PRs from being absolute giant behemoths of reviewing, this PR is setting the stage for a re-shuffling of https://github.com/helium/oracles/pull/856. 
proto: https://github.com/helium/proto/pull/413
This workspace is all about dealing with Service Provider Promotion Fund allocation.
HIP-114
https://github.com/helium/HIP/blob/main/0114-incentive-escrow-fund-for-subscriber-referrals.md
Service Provider Promotions are stored in CarrierV0 on Solana.
To keep the mobile-verifier from talking to a chain, this service will
periodically check Solana and compare Service Providers allocations to
what is stored in S3.
If the values have changed, a new file will be output to a bucket for
the mobile-verifier rewarder to read from.
NOTE: Allocation Values are stored in Bps …
> Promotion Fund workspace

- mobile_verifier/src/rewarder.rs
When fetching mapping events, we constrain correctly by the reward_epoch. When they are removed, we want to keep around a days worth in case we need to debug a days rewards.
> Follow pattern of keeping 1 days worth of info

- Cargo.lock
- Cargo.toml
- file_store/src/cli/dump_mobile_rewards.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/service_provider/promotions/rewards.rs
- mobile_verifier/src/service_provider/reward.rs
- mobile_verifier/tests/integrations/common/mod.rs
- mobile_verifier/tests/integrations/rewarder_sp_rewards.rs
- reward_index/src/indexer.rs
[Proto PR](https://github.com/helium/proto/pull/422)
The groundwork for Service Provider promotions is fine. Some of the finer details are still in flux. 
This PR is disabling any part of service provider promotions that might be written to a public file that would lock us into those proto versions.
> Soft disable Service Provider promotions

- solana/src/burn.rs
- solana/src/lib.rs
- solana/src/start_boost.rs
cargo 1.82.0 clippy complains that the ClientError is potentially too large compared to the rest of the error types, and should be boxed
https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
> Box ClientError

- reward_index/src/indexer.rs
RewardV2 has been written out for some time now, switch indexer over to use it so we can stop writing rewardv1. Stopping the writing of reward_v1 will happen in a separate release.
> Use reward_v2 for Indexing rewards

- mobile_packet_verifier/src/accumulate.rs
- mobile_packet_verifier/src/burner.rs
- mobile_packet_verifier/src/daemon.rs
- mobile_packet_verifier/src/lib.rs
- mobile_packet_verifier/src/pending_burns.rs
Did some refactoring of burner to pull pending_burn logic out to new module
Added new guage `pending_db_burn` with payer label
> Mobile Packet Verifier Add new Metric for pending_dc_burn

- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/service_provider/reward.rs
**TLDR;**
Mixing unit is bad. mmmkay
Previously, for calculating which percentage of rewards a Service provider should receive, the calculation was suing this number as it's base.
`let used_allocation = total_sp_allocation.max(all_transfer);`
`total_sp_allocation` was the maximum number of Bones that could be rewarded in an epoch. `all_transfer` was all the DC transferred in the epoch. Because they were 2 different units, and Bones is at a scale far surpassing DC, the number would always be `total_sp_allocation`.
This is not a problem, until the amount of DC transferred when converted to Bones exceeds the amount allocated.
That leads to a situation where we would assume there is more rewards available than exist. Which in this case lead to matching rewards when there were non unallocated. …
> Fix Service Provider rewards math

- mobile_verifier/src/heartbeats/mod.rs
- mobile_verifier/src/seniority.rs
Under normal circumstances the seniority timestamp for a radio is updated when the first valid hearbeat linked to a new coverage object is processed.  However during this check we skip updating seniority if the reason for the last update was HeartbeatNotSeen.  This check should also skip updating seniority if the last reason was ServiceProviderBan.
> Coverage Object/Heartbeat/Seniority bug

- mobile_verifier/src/seniority.rs
- mobile_verifier/tests/integrations/boosting_oracles.rs
- mobile_verifier/tests/integrations/modeled_coverage.rs
I do no think we need to fix current DB as this does not seem to impact much things.
```
proto::SeniorityUpdate {
key_type: Some(self.key.into()),
new_seniority_timestamp: new_seniority.timestamp() as u64,
reason: update_reason as i32,
new_seniority_timestamp_ms: new_seniority.timestamp_millis() as u64,
},
```
The proto does not care about `inserted_at` anywhere I could find
> Fix inserted_at for seniority  to Utc::now()

- mobile_config/src/client/carrier_service_client.rs
- mobile_verifier/src/cli/mod.rs
- mobile_verifier/src/cli/service_provider_promotions.rs
- mobile_verifier/src/main.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/service_provider/dc_sessions.rs
- mobile_verifier/src/service_provider/promotions.rs
- mobile_verifier/tests/integrations/rewarder_sp_rewards.rs
Fetch from mobile-config the same way they as the rewarder does. Print them in a nice little list.
Running with no options defaults to `Utc::now()`.
```sh
>>> ./mobile-verifier -c ../../mobile-verifier.toml service-provider-promotions 
Service Provider: HeliumMobile
incentive_escrow_bps: 396
Promotions: (1)
name: Referral Elite
duration: 1year 2months 1day 20h 52m 48s (2024-10-29T00:00:00Z -> 2025-12-31T00:00:00Z)
shares: 100
```
Passing the `--start` option.
```sh
>>> ./mobile-verifier -c ../../mobile-verifier.toml service-provider-promotions --start "2024-10-30T00:00:00Z"
Promotions as of 2024-10-30 00:00:00 UTC
Service Provider: HeliumMobile
incentive_escrow_bps: 396
Promotions: (1)
name: Referral Elite
duration: 1year 2months 1day 20h 52m 48s (2024-10-29T00:00:00Z -> …
```
> Add CLI for fetching sp promotions

- Cargo.lock
- Cargo.toml
- boost_manager/Cargo.toml
- Use the official SQLx repository link instead of the fork. It makes future updates a little bit easier and more transparent and we don't have to host fork in our repo. 
- Remove the unused `helium-crypto` dependency from `boost_manager`.
Updating `SQLx` further is currently impossible due to package conflicts, mainly because we are using an outdated Solana library.
Upgrading solana-client, solana-sdk, and solana-program to version ^2 could theoretically resolve these conflicts.
> Use link to sqlx repo instead of fork

- mobile_verifier/migrations/38_coverage_objects_cascade_delete.sql
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/heartbeats/mod.rs
If we run, it will delete:
- Last month = 45k
- Last week = 75K
Total current records 120k
Doing last period and keeping the last 10 valid should delete about 62k coverage objects.
> Clear orphan coverage objects

- file_store/src/file_info_poller.rs
It fixes next compile error if file-store dependency used with `default-features = false` option
```
error[E0433]: failed to resolve: use of undeclared crate or module `sqlx`
--> /home/kurotych/.cargo/git/checkouts/oracles-717ca87c3f481083/833b350/file_store/src/file_info_poller.rs:8:5
|
8 | use sqlx::postgres::PgQueryResult;
|     ^^^^ use of undeclared crate or module `sqlx`
For more information about this error, try `rustc --explain E0433`.
error: could not compile `file-store` (lib) due to 1 previous error
```
> Move sqlx importing under feature directive

- file_store/src/file_store.rs
When a connection problem occurs, downloading a file from AWS hangs.
Add the ability to configure timeout and retry policies in the `file_store`.
> RetryConfig and TimeoutConfig in file_store 

- file_store/src/unique_connections.rs
- mobile_verifier/src/cli/reward_from_db.rs
- mobile_verifier/src/unique_connections/ingestor.rs
When reading a UniqueConnections report from proto, the timestamp was incorrectly converted into seconds.
- Added a test that round trips through proto to make sure timestamps are encoded/decoded properly
- Added logging for processing unique connection reports
- use available unique connections in `reward_from_db` command
> unique connections timestamp

- mobile_verifier/src/rewarder/db.rs
Unique Connections is the outlying query in that it depends on the start _and_ end of a reward_epoch, while the others only care about the end of the reward_epoch.
The different being, unique connections come in once per day, while the others come in constanyl throughout the day.
> Clarify different queries that can prevent rewarding

- coverage_point_calculator/src/lib.rs
- coverage_point_calculator/src/location.rs
- mobile_verifier/src/reward_shares.rs
Radio with:
- 0 average location trust score
- failed speedtest average
- banned
Should not be included in the coverage map.
> Radios that earn 0 rewards should be removed from coverage map

- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/rewarder/boosted_hex_eligibility.rs
- mobile_verifier/src/unique_connections/mod.rs
A radio hitting the unique connection threshold will now be eligible for boosted rewards without having to have the radio thresholds met(3 unique devices with 1mb transferred).  It will also override any service provider ban.
> UniqueConnections make radio eligible for boosted rewards

- boost_manager/tests/integrations/updater_tests.rs
- iot_config/src/client/org_client.rs
- iot_packet_verifier/src/balances.rs
- iot_packet_verifier/src/burner.rs
- iot_packet_verifier/src/daemon.rs
- iot_packet_verifier/src/pending.rs
- iot_packet_verifier/src/verifier.rs
- iot_packet_verifier/tests/integration_tests.rs
- mobile_packet_verifier/src/burner.rs
- solana/src/burn.rs
- solana/src/lib.rs
- solana/src/start_boost.rs
In attempting to bring the `helium-lib` PR https://github.com/helium/oracles/pull/850 back up to speed, and considering the ability to incorporate tracking transactions using `helium-lib`, I was really struggling with all the generics. 
All the times an associated `Error` type was something other than the concrete type used by the actual implementation, it was `()` of `Infallible`. So I thought it would be an okay idea to remove the associated types to make some of the errors paths easier to change up without having to chase down a bunch of generics.
- Removed associated `Error`
- `Orgs` trait
- `SolanaNetwork` trait
- `Debiter` trait
- `ConfigServer` trait
- `PacketWriter` trait
- Removed generics from `Error`
- `BurnError`
- `ConfirmPendingError`
- `VerificationError`
- `MonitorError`
- …
> Make Solana Errors concrete types

- Cargo.lock
- Cargo.toml
- mobile_config/src/gateway_info.rs
- mobile_config/src/gateway_service.rs
- mobile_config/tests/gateway_service.rs
- mobile_verifier/tests/integrations/speedtests.rs
The updated_at field in the response is required to complete the workflow for fetching only the most recently changed hotspots.
This solution is unoptimized since updated_radios is fetched every time. The performance (for v2 endpoints) might be  impacted.
The `updated_radios` hashmap should be cached in future versions.
https://github.com/helium/proto/pull/436
> [Mobile Config] Add updated_at to GatewayInfoV2 (response)

- mobile_config/src/mobile_radio_tracker.rs
- mobile_config/tests/common/mod.rs
- mobile_config/tests/gateway_service.rs
- mobile_config/tests/mobile_radio_tracker.rs
During development testing, we encountered the following issue:
`ERROR mobile_config::mobile_radio_tracker: error in tracking changes to mobile radios err=error returned from database: ON CONFLICT DO UPDATE command cannot affect row a second time`
The root cause of this problem is the existence of duplicate entity keys in the key_to_assets table (on the dev server).
Solution: Handle `(entity_key, asset)` duplicates by fetching unique entries with the newer `refreshed_at`.
(Theoretically possible) Case where one entity_key maps to several different assets will still result in the error described above. Since I don't see a graceful recovery from such data corruption.
> [Mobile Config] Handle entity duplicates in Mobile radio tracker

- boost_manager/src/updater.rs
- file_store/src/file_sink.rs
- iot_config/src/route_service.rs
- iot_verifier/src/runner.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/speedtests.rs
- remove unnecessary lifetimes
- replace `.map_or` with `.is_some_and`
> Clippy updates for 1.84.0

- .github/workflows/CI.yml
- mobile_verifier/src/heartbeats/last_location.rs
- mobile_verifier/src/heartbeats/mod.rs
- mobile_verifier/tests/integrations/last_location.rs
- mobile_verifier/tests/integrations/modeled_coverage.rs
Heartbeats from radios come with a `location_validation_timestamp`, which is the last time a radio had it's location validated.
A `location_validation_timestamp` is valid for up to 24 hours from the first time it was received in a heartbeat.
Previously, we assumed that a heartbeat with a `location_validation_timestamp` had already passed this check. That has been found to not be the case. So "validated heartbeats" were being output with `location_validation_timestamp`'s far in the past.
Now, we are correctly verifying that a `location_validation_timestamp` is within 24 hours of the first received heartbeat that declared it.
> Location Validation Timestamp Cache

- Cargo.lock
- Cargo.toml
- solana/src/burn.rs
- solana/src/lib.rs
- solana/src/sender.rs
- solana/src/start_boost.rs
`helium-lib` PR :: https://github.com/helium/helium-wallet-rs/pull/457
router keys are normally ecc-compact keys, those cannot be turned into solana Pubkeys. But they can still be used to derive the escrow accounts from.
Updating helium-lib, it has moved from using a regular `solana::Transaction` to `solana::VersionedTransaction`.
> update helium-lib to take router_key as a string

- solana/src/burn.rs
Delegate accounts are found through `key()` -> `token()` -> `sub_dao` specific addresses.
> Use the SubDao when finding delegate and escrow accounts

- solana/src/burn.rs
- solana/src/sender.rs
In Oracle's we have historically had `skip_preflight: true` for all txns.
There have been updates to helium-lib that we cannot debug if preflight checks are skipped. 
This PR turns it into a setting, so it can toggle when we need better errors.
> Add skip_preflight setting for solana rpc

- .github/workflows/CI.yml
- rust-toolchain.toml
- Do not require `release_version` for manual trigger. The  release job will check for that or skip if left empty.
- Everything now runs in a container `ubuntu:20.04`, this makes runs more consistent.
- Tests are now run on a matrix generated prior based on `cargo metadata` so that new added tests or packages are not left out.
- Caching is now only for release as it seems to be faster to run test in a matrix individually without waisting 1min to pull cache. When releasing, a job to build the release will start right away and the upload job will wait for `[build-release, fmt, clippy, tests]`  to be completed.
Notes:
- I soon as we move away from `ubuntu:20.04` we should be able to remove the `Install Dependencies` step, saving us around 30s on every job.
- Cache is hardcoded to …
> Latest CI updates

- Cargo.lock
- reward_index/Cargo.toml
- reward_index/pkg/settings-template.toml
- reward_index/src/indexer.rs
- reward_index/src/main.rs
- reward_index/src/settings.rs
- use TaskManager for Server
- impl ManagedTask for Indexer
- Create and use single FileStore
- make `unallocated_reward_entity_key` required setting
- format `tokio::select!`
- restructure Settings and settings-template.toml to match
- Update Settings Environment override with more applicable prefix and separator
The Environment separator needs to be a `__` (double underscore) so settings with underscores parse correctly.
With a separator of `_` (single underscore)
`RI_operation_fund_key=fund_key` will parse to `operation.fund.key = "fund_key"`
With a separation of `__` (double underscore)
`RI__operation_fund_key` will parse to `operation_fund_key = "fund_key"`
> Update Reward Indexer to use TaskManager

- mobile_config/src/client/authorization_client.rs
- mobile_verifier/src/radio_threshold.rs
- mobile_verifier/src/sp_boosted_rewards_bans.rs
- mobile_verifier/src/subscriber_location.rs
- mobile_verifier/src/subscriber_verified_mapping_event.rs
- mobile_verifier/src/unique_connections/ingestor.rs
In every use case, these trait bounds are required.
> Always require AuthorizationVerifier be Send + Sync + 'static

- boost_manager/src/main.rs
- file_store/src/file_info_poller.rs
- file_store/src/file_sink.rs
- iot_packet_verifier/src/daemon.rs
- iot_verifier/src/main.rs
- mobile_packet_verifier/src/daemon.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/heartbeats/cbrs.rs
- mobile_verifier/src/heartbeats/wifi.rs
- mobile_verifier/src/radio_threshold.rs
- mobile_verifier/src/sp_boosted_rewards_bans.rs
- mobile_verifier/src/speedtests.rs
- mobile_verifier/src/subscriber_location.rs
- mobile_verifier/src/subscriber_verified_mapping_event.rs
- mobile_verifier/src/unique_connections/ingestor.rs
- reward_index/src/main.rs
Providing defaults for `FileInfoPollerServer` to the most used types allows us to cleanup a lot of the generic code around `continuous_source()`.
```rs
pub struct FileInfoPollerServer<
Message,
State = PgPool,
Store = FileStore,
Parser = MsgDecodeFileInfoPollerParser,
>
```
> file store qol

- coverage_point_calculator/src/lib.rs
- coverage_point_calculator/src/location.rs
- mobile_verifier/src/reward_shares.rs
Return error in `average_distance` and `multiplier` functions instead of panic
> Return error in `average_distance` and `multiplier` functions instead of panic

- coverage_point_calculator/src/lib.rs
- hex_assignments/src/assignment.rs
- mobile_verifier/tests/integrations/boosting_oracles.rs
HRP-20250409 https://github.com/helium/helium-release-proposals/blob/main/releases/20250409-core-devs.md#1-hip-103-urban-area-multiplier-adjustment
> update footfall C hexes to have a multipler of 0.03

- file_store/src/file_info_poller.rs
Add a new metric to file_info_poller to record the timestamp of the file currently being processed.  Idea is to write alerts in the form of `time() - file_info_poller_timestamp` which will alert if the service has no new files to pick up
the current metric outputs `Utc::now() - file_timestamp` which will not alert until a new value is picked up.  Should we remove current metric?
> Add new metric for latest file_info_poller file timestamp

- iot_verifier/src/reward_share.rs
- iot_verifier/tests/integrations/common/mod.rs
- iot_verifier/tests/integrations/rewarder_operations.rs
- iot_verifier/tests/integrations/rewarder_oracles.rs
- iot_verifier/tests/integrations/rewarder_poc_dc.rs
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/service_provider/reward.rs
- mobile_verifier/tests/integrations/common/mod.rs
- mobile_verifier/tests/integrations/hex_boosting.rs
- mobile_verifier/tests/integrations/rewarder_mappers.rs
- mobile_verifier/tests/integrations/rewarder_oracles.rs
- mobile_verifier/tests/integrations/rewarder_poc_dc.rs
- mobile_verifier/tests/integrations/rewarder_sp_rewards.rs
Tests where the values were different were testing percentages rather than anything specific to EpochRewardInfo.
> name rewards_info helpers and use static values

- mobile_config/migrations/20250411184550_add_banning_key_role.sql
- mobile_config/src/lib.rs
This key supports submitting gateway bans to the ingester.
Fix the `"ban"` string representation to `"banning"` to match the sqlx type name on the enum.
> Add migration for banning key type

- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/speedtests.rs
- mobile_verifier/src/speedtests_average.rs
- mobile_verifier/tests/integrations/common/mod.rs
- mobile_verifier/tests/integrations/hex_boosting.rs
- mobile_verifier/tests/integrations/rewarder_mappers.rs
- mobile_verifier/tests/integrations/rewarder_oracles.rs
- mobile_verifier/tests/integrations/rewarder_poc_dc.rs
- mobile_verifier/tests/integrations/rewarder_sp_rewards.rs
- mobile_verifier/tests/integrations/speedtests.rs
Provide a testing FileSink that acks messages as they're written so we don't have to deal with race conditions in tests.
```rs
let (_, rewards) = tokio::join!(
rewarder::reward_mappers(&pool, &mobile_rewards_client, &reward_info),
receive_expected_rewards(&mut mobile_rewards)
);
```
Tests required that you know how many messages you were expecting, otherwise the test would hang indefinitely either waiting for a written message to be acknowledged, or waiting for a message that would never be written.
The test `FileSinkReceiver` consumes all messages that are written as they come.
Functions in the rewarder now own a `FileSinkClient<T>`
```rs
pub async fn reward_poc_and_dc(
pool: &Pool<Postgres>,
hex_service_client: &impl HexBoostingInfoResolver<Error = ClientError>,
mobile_rewards: …
```
> Nonblocking rewards sink for tests

- hex_assignments/src/assignment.rs
- hex_assignments/src/footfall.rs
- hex_assignments/src/landtype.rs
- hex_assignments/src/lib.rs
- hex_assignments/src/service_provider_override.rs
- hex_assignments/src/urbanization.rs
- mobile_verifier/src/boosting_oracles/data_sets.rs
- mobile_verifier/tests/integrations/boosting_oracles.rs
- mobile_verifier/tests/integrations/common/mod.rs
We can remove some amount of indirection in hex boosting by reifying generics to types that are already supported.
> Remove Generics around HexAssignments

- mobile_verifier/src/rewarder.rs
- mobile_verifier/src/speedtests_average.rs
- mobile_verifier/tests/integrations/hex_boosting.rs
- mobile_verifier/tests/integrations/rewarder_poc_dc.rs
Talking with @riobah , writing out speedtest_avg files during rewarding that are limited to the end of the epoch is causing confusion and now that `radio_reward_v2` includes the speedtest_avg there is no need to write them out anymore.
> Stop writing out speedtest_avg files during rewarding

- file_store/src/usage_counts.rs
Fixing issue where timestamp should be in milliseconds instead of seconds [see here](https://github.com/helium/proto/blob/master/src/service/poc_mobile.proto#L29).
> Update UsageStatsReqV1 timestamp to ms

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- aws_local/src/lib.rs
- mobile_verifier/migrations/51_add_ent_key_to_subscr_map_act.sql
- mobile_verifier/src/reward_shares.rs
- mobile_verifier/src/subscriber_mapping_activity.rs
- mobile_verifier/src/subscriber_mapping_activity/db.rs
- mobile_verifier/tests/integrations/common/mod.rs
- mobile_verifier/tests/integrations/rewarder_mappers.rs
- mobile_verifier/tests/integrations/subscriber_map_act_daemon.rs
- reward_index/src/extract.rs
- reward_index/tests/integrations/mobile.rs
- Handle `reward_override_entity_key` in SubscriberMappingActivityIngestReportV1 report.
- Add `reward_override_entity_key` field to the `subscriber_mapping_activity` table
- Add `reward_override_entity_key` to SubscriberReward proto
- Handle `reward_override_entity_key` in reward_index (override the key/address in reward_index table)
> Add reward_override_entity_key to subscriber mapping activity

- Cargo.lock
- Cargo.toml
- boost_manager/Cargo.toml
- file_store/Cargo.toml
- file_store/src/file_info.rs
- iot_verifier/Cargo.toml
- iot_verifier/src/hex_density.rs
- iot_verifier/src/poc.rs
- iot_verifier/src/reward_share.rs
- iot_verifier/src/runner.rs
- iot_verifier/tests/integrations/runner_tests.rs
- mobile_config/Cargo.toml
- mobile_config/src/boosted_hex_info.rs
- mobile_config/src/gateway_info.rs
- mobile_verifier/Cargo.toml
- mobile_verifier/src/boosting_oracles/data_sets.rs
- reward_index/Cargo.toml
`LazyLock` was stabilized in `1.80`, we can drop our dependency on `lazy_static`. This frees us up from having to keep the dependency up to date with libraries that are still using it.
This PR is preparing for further updates to aws dependencies
> migrate lazy_static -> std::sync::LazyLock

- mobile_config/src/main.rs
- mobile_config/src/mobile_radio_tracker.rs
- mobile_config/tests/common/mod.rs
- mobile_config/tests/gateway_service.rs
- mobile_config/tests/mobile_radio_tracker.rs
`asserted_location_changed_at`  = `refreshed_at` if a new (arrived) radio has location.
Add PostMigrateMobileTracker command to fill in missing values caused by a bug
Ex:
`RUST_LOG=debug .mobile-config -c ./mobile-config.toml post-migrate-mobile-tracker`
> Fix TrackedMobileRadio asserted_location_changed_at

- file_store/src/error.rs
This fixes an error for project uses file-store.
```
error[E0277]: `?` couldn't convert the error to `file_store::Error`
--> cas/src/etl/verified_hotspot_data_transfer_session.rs:117:53
|
117 |             status: ReportStatus::try_from(v.status)?,
|                     --------------------------------^ the trait `From<UnknownEnumValue>` is not implemented for `file_store::Error`
|                     |
|                     this can't be annotated with `?` because it has type `Result<_, UnknownEnumValue>`
|
= note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
= help: the following other types implement trait `From<T>`:
`file_store::Error` implements `From<Box<dyn derive_more::Error + std::marker::Send + Sync>>` …
```
> cast helium_proto::UnknownEnumValue to file-store error

- aws_local/src/lib.rs
Match the function requirements of `file_sink::FileSinkBuilder::new`  where `file_type` can be anything that `impl ToString`. 
This allows projects outside Oracles to use `aws_local` to test with  file types that may only be local to their project.
> Loosen FileType restrction for aws_local testing

- file_store/src/file_info_poller.rs
- file_store/src/mobile_ban.rs
- iot_packet_verifier/src/daemon.rs
- iot_verifier/src/main.rs
- mobile_packet_verifier/src/daemon.rs
- mobile_verifier/src/banning/sp_boosted_rewards_bans.rs
- mobile_verifier/src/coverage.rs
- mobile_verifier/src/data_session.rs
- mobile_verifier/src/heartbeats/wifi.rs
- mobile_verifier/src/speedtests.rs
- mobile_verifier/src/subscriber_mapping_activity.rs
- mobile_verifier/src/unique_connections/ingestor.rs
- mobile_verifier/tests/integrations/subscriber_map_act_daemon.rs
- reward_index/src/main.rs
Add new setters that are prefixed with `lookback_` to make them discoverable when setting `lookback`, and it’s a nice place to hang some documentation
> FileInfoPollerConfigBuilder add builder setter
