helium/oracles

.github/workflows/rust.yml
- Add the entropy server to the build system
- Bump cargo deb GHA version
=> Add entropy; bump cargo deb GHA

.github/workflows/rust.yml
run the cargo unit test suite as part of CI
=> run cargo test as part of ci

Cargo.lock, entropy/src/entropy_generator.rs, entropy/src/main.rs, lora_verifier/src/loader.rs, lora_verifier/src/traits/b64.rs, store/src/cli/bucket.rs, store/src/cli/info.rs, store/src/file_info.rs, store/src/file_sink.rs
* Use entropy version
* Rename to entropy_report_v1
=> Entropy updates

ingest/src/server_5g.rs
This is a temporary change to have the mobile ingestor output both the requests and ingest reports for both heartbeats and speedtests.  
This will allow the mobile verifier, which reads the ingest reports, to run while mobile rewards, which reads the requests, remains unchanged.
=> Change mobile ingestor to output both the hearbeat and speedtest requests and well as ingest reports

lora_verifier/src/loader.rs
Previously the loaded was assuming the entropy would be in the ingest store.  This changes that so that it loads from its own distinct store
=> load entropy from its distinct store

lora_verifier/src/poc.rs, mobile_rewards/src/keypair.rs, mobile_rewards/src/traits/txn_sign.rs, poc_iot_injector/src/keypair.rs
=> simplify keypair.rs

Cargo.lock, file_store/Cargo.toml, file_store/src/lora_beacon_report.rs, file_store/src/lora_witness_report.rs, file_store/src/traits/mod.rs, file_store/src/traits/report_id.rs, ingest/src/server_lora.rs, poc_iot_verifier/src/follower.rs, poc_iot_verifier/src/loader.rs, poc_iot_verifier/src/meta.rs, poc_iot_verifier/src/poc.rs, poc_iot_verifier/src/poc_report.rs, poc_iot_verifier/src/runner.rs
Includes a bunch of fixes identified from testing with real data on mainnet.  Also some refactor to centralise report ID generation
=> misc fixes from mainnet testing

file_store/src/file_sink.rs, file_store/src/file_source.rs
Next question: how do we modify the API for the file store to take in a maximum size? Or do we set it to 2^32 - 1?
=> Fix max_frame_length for LengthDelimitedCodec

poc_iot_injector/src/cli/generate.rs, poc_iot_injector/src/lib.rs, poc_iot_injector/src/receipt_txn.rs, poc_iot_injector/src/server.rs
Summary
----
This doesn't change any functionality just switches stream processing to be more concurrent.
=> Switch to for_each_concurrent for processing

poc_mobile_verifier/src/lib.rs, poc_mobile_verifier/src/scheduler.rs, poc_mobile_verifier/src/verifier.rs
Created Scheduler struct which now houses all timing logic for the poc_mobile_verifier.
=> Refactor timing logic out to separate Scheduler struct

poc_mobile_verifier/src/speedtests.rs
This is a fun thing you can do with rust enums!
=> Clean up speedtest tier comparisons

poc_iot_verifier/migrations/6_entropy_start_time.down.sql, poc_iot_verifier/migrations/6_entropy_start_time.up.sql, poc_iot_verifier/src/poc_report.rs
=> Revert "Fix poc_report join query and add entropy_start_time migration"

file_store/src/speedtest.rs, poc_mobile_verifier/src/cli/generate.rs, poc_mobile_verifier/src/heartbeats.rs, poc_mobile_verifier/src/ingest.rs, poc_mobile_verifier/src/lib.rs, poc_mobile_verifier/src/speedtests.rs, poc_mobile_verifier/src/verifier.rs
This one is quite a doozy. If you have any questions be sure to ask, the mechanics of getting async working was pretty complicated so there's a lot of teachable stuff here.
One particularly proud moment was completely avoiding any use of "box".
=> Convert validation of heartbeats and speedtests to use a stream

poc_iot_verifier/src/poc_report.rs, poc_iot_verifier/src/runner.rs
Handles the entropy timestamp field being optionally returned from various poc report queries.  Defaults to Option None if not present.
Fixes some typos in queries
=> Entropy related fixes

poc_iot_injector/src/cli/server.rs, poc_iot_injector/src/receipt_txn.rs, poc_iot_injector/src/server.rs
Fixes some issues while doing first deployment.
=> Fix file_upload and add extra debug logs

poc_iot_injector/src/server.rs
poc-injector server would inconsistently crash trying to connect to blockchain-node for no reason even when `do_submission` is set to false.
Potentially bypass the error by not creating `TxnService` at all unless `do_submission` is set to true.
=> Only create txn_service if do_submission is true

file_store/src/error.rs, file_store/src/lora_beacon_report.rs, file_store/src/lora_invalid_poc.rs, file_store/src/lora_witness_report.rs, poc_iot_verifier/src/error.rs, poc_iot_verifier/src/runner.rs
- Introduce more specific errors when handling reports
=> Remove usage of Custom error type

poc_iot_injector/src/server.rs
- This changes the poc-iot-injector server's stream processing back to `for_each_concurrent` with explicitly tracing each error, primarily for debugging purposes. Hopefully we can catch the exact place at which the injector fatally fails and debug it further if we can. Otherwise, the hope is that at the minimum this change wouldn't bring down the whole system.
=> Debug each error explicitly for txn submission

poc_iot_verifier/src/gateway_cache.rs
`PublicKey`'s `PartialOrd` implementation unfortunately does a heap allocation. We discovered this while doing some profiling. By using a PublicKey for a BTreeMap's key type, every single tree walk comparison requires at least one heap allocation. It may actually require two if the compiler doesn't optimize awat the redundant string conversion for the not-changing key.
Ideally, we would not allocate at all, but first, compare network tags, then compare key bytes. A quick glance at the crypto code leads me to believe that we don't have access to the internals.
=> GW chache: pre-convert PK to vec to avoid costly comparisons

Cargo.toml
small change to the release build profile to incorporate debug symbols into all builds
=> add debug symbols to all builds

poc_iot_injector/src/cli/generate.rs, poc_iot_injector/src/receipt_txn.rs, poc_iot_injector/src/server.rs
- Simplify submission error handling
- Fix function calls
- Also removes the file_sink_write when `do_submission` is set to `true`.
=> Switch txn submission to use JoinSet

poc_iot_verifier/migrations/8_bootstrap_next_reward.sql
need to bootstrap both reward cycle meta table values
=> adding bootstrap val for iot next reward

poc_iot_verifier/migrations/7_bootstrap_reward_time.sql, poc_iot_verifier/migrations/8_bootstrap_next_reward.sql, poc_iot_verifier/src/reward_share.rs
this bad sql statement is crashing the runner when trying to insert records into the reward_share table
=> typo in sql statement fix

poc_iot_verifier/src/reward_share.rs, poc_iot_verifier/src/runner.rs
This change adds some guards to the hex scaling factor and reward unit handling to:
- avoid zero-division errors if the total reward shares are zero
- early filtering of the reward shares by not adding records to the db if the reward_units is 0 which should only happen if an otherwise valid beacon has no valid witnesses. the reasoning being that, as reward shares is the product of `reward_unit * hex_scaling_factor` that if either of those two is 0 the result will be 0 as well so no rewards will be given
- at this point, it should technically be impossible for a valid PoC to have 0 for hex scaling factor b/c these beacons/witnesses are filtered out in the validation phase but for completeness i'm explicitly filtering if _either_ reward share component is 0
This change also rounds the …
=> filter zero units; guard on zero-division

poc_iot_injector/src/receipt_txn.rs
This ensures that we never construct a poc receipt txn for submission if there are zero witnesses. It's effectively wasteful to submit such transactions and they don't contribute to rewards anyway.
=> Dont construct receipt txn for 0 witnesses

iot_verifier/src/poc_report.rs
Cant use table names with `ON CONFLICT DO....`
=> fix conflict sql for bulk inserts

poc_iot_injector/src/receipt_txn.rs
=> Make construct_poc_receipt and construct_path_element infallible

Cargo.lock, file_store/src/traits/msg_verify.rs, iot_config/src/gateway_service.rs, iot_config/src/lib.rs, iot_config/src/lora_field.rs, iot_config/src/org.rs, iot_config/src/org_service.rs, iot_config/src/route.rs, iot_config/src/route_service.rs, iot_config/src/session_key_service.rs
- add logging for DB save errors
- add GrpcStreamRequest
- remove devaddr_ranges and eui_pairs from Route
- unimplemented session key filter rpcs
- unimplemented gateway service rpcs
Things to discuss:
- owner_pubkey unique?
- requiring routes to have a protocol?
- enable/disable per route.
=> iot-config with streaming proto rpcs

iot_verifier/src/runner.rs
We have previously been (incorrectly) assigning reward units to all witnesses and beacons based on the beaconer reward calculations defined in HIP. This PR corrects that calculation and applies it _only_ to the beaconer report as well as implements the rewards_per_witness side of the calculations and applies them to the witness reports for valid pocs
=> accommodate both sides of hip 15 calcs

Cargo.lock, iot_config/migrations/4_regions.sql, iot_config/src/gateway_service.rs, iot_config/src/region_map.rs
Also update helium-crypto to update solana-sdk and address a Verify trait bug when the message in question isn't the expected length
=> Fix queries for setting and getting region index files

Cargo.lock, iot_config/migrations/2_organizations.sql, iot_config/migrations/3_routes.sql, iot_config/migrations/5_hpr_keys.sql, iot_config/src/lora_field.rs, iot_config/src/org.rs, iot_config/src/org_service.rs, iot_config/src/route.rs, iot_config/src/route_service.rs
Address changes to the iot config proto and separate HPR authorizing key access from admin user key
=> update for proto changes; hpr keys

iot_verifier/src/poc.rs
push up location assertion verification
push down beacon construction verification, perform the `cheaper` verifications first
=> tweak beacon verification order

iot_verifier/src/poc.rs
Adds test to confirm the expected list of verifications are being applied to both witnesses and beacons.  For each verification we setup a witness or a beacon report with bad data that will result in the expected verification returning a fail and we assert that.  
If for example a verification was removed from the verification list the test will pick up on that and result in a test failure.  This guards against the recent case where the capability check was dropped unknowingly from the witness verification list resulting in dataonly gateways being able to participate in POC
=> refactor and add tests to confirm all expected verifications are being run

iot_verifier/src/entropy_loader.rs
=> Revert "Change entropy id to hash of entire report"

iot_verifier/src/poc_report.rs
=> Revert "Update query to pull beacons from db"

Cargo.lock, poc_iot_injector/src/receipt_txn.rs
=> Remove hex_scale and reward_unit from receipts

price/src/lib.rs, price/src/metrics.rs, price/src/price_generator.rs
Summary
----
This adds several price related metrics. Specifically a counter for update and a gauge to track the actual price value.
=> Add price metrics

mobile_verifier/src/heartbeats.rs
**Problem**: When the mobile-verifier wakes up to process a batch of heartbeats it grabs all ingest files with a timestamp in the 3 hour window.  Some heartbeats in the last file read in are likely to be outside of the 3 hour window and are marked invalid.
**Solution**: We add the mobile ingest roll time (15 minutes) to the end of the 3 hour window before validating any heartbeats.
This will be cherry picked across to the `helium-l1-maint` branch and released before April 18th
=> Update mobile verifier to add mobile ingest roll time to end of epoch when validating heartbeats

iot_config/src/admin_service.rs, iot_config/src/gateway_service.rs, iot_config/src/lib.rs, iot_config/src/org_service.rs, iot_config/src/route_service.rs, iot_config/src/session_key_service.rs, iot_config/src/telemetry.rs
back-port metrics PR for iot-config service into the maintenance branch
=> add iot-config metrics

mobile_config/src/admin_service.rs, mobile_config/src/gateway_service.rs, mobile_config/src/lib.rs, mobile_config/src/router_service.rs, mobile_config/src/telemetry.rs
add basic grpc request count metrics to the mobile config service
=> add grpc request count metrics to mobile config

iot_config/src/gateway_service.rs, iot_config/src/route_service.rs, iot_config/src/session_key_service.rs, iot_config/src/telemetry.rs, mobile_config/src/gateway_service.rs, mobile_config/src/telemetry.rs
add gateway lookup result metrics (gateway is found on-chain, asserted or not-asserted) and correctly decrement stream subscribers when the client-side disconnects
=> register additional gateway metrics related to chain assert status

file_store/src/entropy_report.rs, iot_verifier/migrations/10_gateway_dc_shares.sql, iot_verifier/pkg/settings-template.toml, iot_verifier/src/gateway_cache.rs, iot_verifier/src/loader.rs, iot_verifier/src/poc.rs, iot_verifier/src/region_cache.rs, iot_verifier/src/reward_share.rs, iot_verifier/src/runner.rs, iot_verifier/src/settings.rs
Misc fixes from local testing of the iot verifier using mainnet POC data.  Tests were run with a backlog of 24hrs worth of data
=> IOT Verifier fixes

solana/src/lib.rs
=> If no account, there's no DC

iot_verifier/src/reward_share.rs
=> Revert "set packet reward share ts to that of packet ts"

iot_packet_verifier/src/verifier.rs, mobile_packet_verifier/src/burner.rs, mobile_verifier/src/reward_shares.rs
After running through all available data transfer requests:
```
{
"hotspot": "1128AwN9aWwzcHNKJwga4XvepMPPZcoBrbC6ZfqPqzL1zDGpX4AY",
"num_dcs": 289850,
"total_bytes": 5796988160
}
{
"hotspot": "11rqZKUsUzko3rGacnBcm9kypXDMsFhj21wE7TkGbYRrwhDvMJi",
"num_dcs": 9285,
"total_bytes": 185694531
}
{
"hotspot": "1124Ywnbi465MMddtYUotGdw67UAgxKb3iSitRBpD2nvfobkeGGg",
"num_dcs": 2772,
"total_bytes": 55434672
}
{
"hotspot": "11rQuGuVHPypR7CsnNjuJX3nxVLQgizGPaSETrD4QgEDYZy4ATF",
"num_dcs": 61876,
"total_bytes": 1237518418
}
{
"hotspot": "11Ao1eckVoJS21pxSXRKgTfcmAztU7PkDGPuX3wBtfEojcYRiFF",
"num_dcs": 95,
"total_bytes": 1883616
}
{
"hotspot": "112EwdueX6wjZxwugh45pWmZDkYkAihKLh2qC1iDAoofkEQHyj4K",
"num_dcs": 17159,
"total_bytes": 343173839
}
{
"hotspot": …
```
=> Fix mobile packet verifier rewards and burns

Cargo.lock, mobile_verifier/src/heartbeats.rs
relies on https://github.com/helium/proto/pull/321
=> update heartbeat invalid reason to new correct option

Cargo.lock, iot_config/src/route.rs
requires https://github.com/helium/proto/pull/327
=> add receiver_nsid field to http protocol

Cargo.lock, file_store/src/iot_valid_poc.rs, iot_verifier/src/poc.rs, iot_verifier/src/runner.rs
proto pr: https://github.com/helium/proto/pull/328
=> include gain and elevation in valid beacon and witness reports

Cargo.lock, file_store/src/cli/dump.rs, file_store/src/file_info.rs, file_store/src/iot_packet.rs, file_store/src/lib.rs, file_store/src/mobile_subscriber.rs, file_store/src/traits/msg_verify.rs, ingest/src/server_mobile.rs, iot_packet_verifier/tests/integration_tests.rs
Linked proto pr: https://github.com/helium/proto/pull/330
Add support for subscriber location reports at the ingestor level
=> Support subscriber location requests via ingestors

price/src/cli/check.rs, price/src/cli/mod.rs, price/src/lib.rs, price/src/main.rs
Add a price cli to show if current price is valid
`cargo run -p price -- check --iot`
`cargo run -p price -- check --mobile`
=> Add price check cli to determine if price is currently valid

iot_verifier/src/gateway_updater.rs
Whilst running the IOT verifier locally over the previous epoch 24 hrs worth of history, encountered an issue whereby the refreshed gateway map received from iot config service was zero.  This was then sent to the consumers ( hex density scaler and the cache ) resulting in all poc reports failing verification.
`
2023-06-06T11:32:28.012131Z  INFO iot_verifier::gateway_updater: completed refreshing gateways, total gateways: 0
2023-06-06T11:32:28.149578Z  INFO iot_verifier::tx_scaler: density_scaler: generating hex scaling map, starting at 2023-06-04T11:32:28.149576Z
2023-06-06T11:32:30.969204Z  INFO iot_verifier::tx_scaler: density_scaler: scaling factor map entries: 0
`
This adds a guard so that in this scenario the refreshed map is dropped, and not sent to consumer.
A more robust solution …
=> dont send empty gateway list to consumers

Cargo.lock, db_store/src/error.rs, db_store/src/iam_auth_pool.rs, file_store/Cargo.toml, file_store/src/error.rs, file_store/src/file_info.rs, file_store/src/file_store.rs
This reverts commit 962cf8bbf1aecff62072c9e91dbc1050c38aa5c6.
=> Revert "Update aws and tempfile libs (#550)"

iot_verifier/src/runner.rs
change to first to arrive witness selection from random witness selection
=> change to first to arrive witness selection

Cargo.lock, Cargo.toml, file_store/src/file_info.rs, file_store/src/speedtest.rs, iot_verifier/src/poc.rs, mobile_verifier/src/cli/server.rs, mobile_verifier/src/speedtests.rs
linked proto branch: https://github.com/helium/proto/pull/365
Writes out the verification/validity status of a speedtest to S3
=> write out verified status of speedtests to s3

Cargo.lock, Cargo.toml, file_store/src/file_sink.rs, file_store/src/traits/msg_verify.rs, ingest/Cargo.toml, ingest/src/server_iot.rs, ingest/src/settings.rs
Proto: https://github.com/helium/proto/pull/370
=> Add bi directional stream for beacons/witnesses

Cargo.lock, denylist/Cargo.toml, denylist/src/denylist.rs, denylist/src/error.rs, iot_verifier/src/poc.rs
This allows use of the new v2 filter types without having to implement it all here
=> Switch to using xorf_generator as a crate

mobile_verifier/src/subscriber_location.rs
With the Helium Mobile subscriber discovery mapping ingest pipeline stabilizing, this change re-institutes the minimum requirement for mapping events to be occurring in order for subscribers to receive rewards during a given rewardable period. Based on the current const in this change, the mobile carrier will need to verify a subscriber has met the mapping requirement (number of mapping events) once per rewardable period (24 hr period) to receive rewards for that period.
=> reinstitute mapping event requirements for active mobile subs

mobile_verifier/src/reward_shares.rs
=> Filter out any data transfer rewards that are zero

Cargo.lock, iot_verifier/Cargo.toml, iot_verifier/src/gateway_updater.rs, iot_verifier/src/hex_density.rs, iot_verifier/src/lib.rs, iot_verifier/src/main.rs, iot_verifier/src/poc.rs, iot_verifier/src/purger.rs, iot_verifier/src/region_cache.rs, iot_verifier/src/runner.rs, iot_verifier/src/settings.rs, iot_verifier/src/tx_scaler.rs, iot_verifier/tests/common/mod.rs, iot_verifier/tests/purger_tests.rs, iot_verifier/tests/runner_tests.rs
Adds runner integration test, making use of the iot config trait
=> iot verifier integration tests

Cargo.lock, Cargo.toml, iot_config/Cargo.toml, iot_config/migrations/20231101175438_track_deletes.sql, iot_config/src/admin.rs, iot_config/src/db_cleaner.rs, iot_config/src/lib.rs, iot_config/src/main.rs, iot_config/src/org_service.rs, iot_config/src/route.rs, iot_config/src/route_service.rs, iot_config/src/settings.rs, iot_config/tests/route_service.rs
Requires tracking deletions in the database.
Proto Change: https://github.com/helium/proto/pull/374
Not done: process to actuall delete the records from the db after 48 hours
=> Update iot-config to support only sending changes since a certain timestamp to caller

Cargo.lock, Cargo.toml
Went and merged https://github.com/helium/oracles/pull/663 prior to merging the proto
this repoints oracles to use proto master
=> point proto to master

iot_verifier/src/reward_share.rs, iot_verifier/src/rewarder.rs, iot_verifier/tests/rewarder_operations.rs
Addressing review comments in this PR rather than on the original in case we dont have time to get the changes tested, review and merged
=> refactor and address review comments

file_store/src/file_sink.rs
```
2024-01-23T19:29:08.306571Z ERROR file_store::file_upload: failed to remove uploaded file /tmp/mobile-ingest/data/wifi_heartbeat_report.1696344950810.gz: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
This error was caused because file_sinks on init looked in the sink work dir for any files that were left over from a previous run and if auto_commit is on it will then send the file to the file_uploader.  It then checked the file_upload dir for any files left over but misinterprets the file that was just moved there from the first check as left over from a previous run.  Changed the sequence to check the upload work dir first and then sink work dir should fix the problem.
=> Change order that file_sink looks for unfinished work

mobile_verifier/src/heartbeats/cbrs.rs
This reverts commit 195b925b05c95b03bb3bf68b37d0d77e4d69ad96.
=> Revert "process all cbrs heartbeats, remove filtering"

mobile_verifier/src/coverage.rs, mobile_verifier/tests/modeled_coverage.rs
https://github.com/helium/HIP/blob/main/0105-modification-of-mobile-subdao-hex-limits.md
* cbrs and wifi are no longer compared to each other, each is independent
* outdoor coverage multipliers updated
Still looking at adding some additional testing
=> Implementation of HIP-105

Cargo.lock, file_store/src/error.rs, file_store/src/file_info.rs, file_store/src/lib.rs, file_store/src/mobile_radio_invalidated_threshold.rs, file_store/src/traits/msg_verify.rs, ingest/src/server_mobile.rs, mobile_verifier/migrations/27_subscriber_radio_threshold.sql, mobile_verifier/src/cli/reward_from_db.rs, mobile_verifier/src/cli/server.rs, mobile_verifier/src/lib.rs, mobile_verifier/src/radio_threshold.rs, mobile_verifier/src/reward_shares.rs, mobile_verifier/src/rewarder.rs, mobile_verifier/tests/boosting_oracles.rs, mobile_verifier/tests/hex_boosting.rs, mobile_verifier/tests/modeled_coverage.rs
=> ingestor and filestore support for invalidated threshold reports

file_store/src/mobile_radio_threshold.rs, mobile_verifier/migrations/28_radio_threshold_cbsd_id_emptry_strings.sql, mobile_verifier/src/radio_threshold.rs, mobile_verifier/tests/hex_boosting.rs
Modified existing test and added 2 more
=> Convert empty string to None for cbsd_id in radio_threshold

boost_manager/tests/activator_tests.rs, boost_manager/tests/watcher_tests.rs, mobile_config/src/boosted_hex_info.rs, mobile_verifier/src/coverage.rs, mobile_verifier/src/reward_shares.rs, mobile_verifier/tests/hex_boosting.rs, mobile_verifier/tests/modeled_coverage.rs
Also redefines boost multipliers as NonZeroU32 rather than u32
=> determine oracle multiplier based on boost value >=1

mobile_verifier/src/coverage.rs, mobile_verifier/src/reward_shares.rs, mobile_verifier/tests/integrations/boosting_oracles.rs, mobile_verifier/tests/integrations/hex_boosting.rs, mobile_verifier/tests/integrations/modeled_coverage.rs, mobile_verifier/tests/integrations/rewarder_poc_dc.rs
HIP: https://github.com/helium/HIP/blob/main/0113-reward-cbrs-as-experimental.md
Want to take another pass through and see if some of the tests can be change to not test the exact rewards amount since tests seem brittle.
=> Implement HIP-113 - Cannot be deployed until 2024-05-10

iot_verifier/src/runner.rs
This takes care of some housekeeping, shifting some furniture around and a lil tidy up of some rough edges
=> runner refactor/tidy

Cargo.lock, price/src/price_generator.rs
New helium-lib changes how connections are passed
=> Update to latest helium-lib

coverage_point_calculator/src/lib.rs, coverage_point_calculator/src/speedtest.rs, file_store/src/speedtest.rs
Adds additional changes to support the verification verifier
=> Verification mapping verifier additional requirements

mobile_config/src/carrier_service.rs, mobile_config_cli/src/client.rs, mobile_config_cli/src/cmds/carrier.rs, mobile_config_cli/src/cmds/mod.rs, mobile_config_cli/src/main.rs
- Add mobile-config-cli carrier service command
- Fix trying to verify the pubkey of the wrong field of a request
=> mobile config list programs fix

file_store/src/file_store.rs
In continuation to https://github.com/helium/oracles/pull/911
Actually it is not only refactoring but also providing "local" feature to the `new` function (what I was missed in previous PR)
=> Refactor file store constructor

solana/src/lib.rs
There's currently no way to go directly from a solana Keypair to a
helium-lib Keypair, except through a bytes translation.
We should add the conversion to helium-lib.
We need to be using helium-lib Keypairs because all the functions that
construct transactions expect it.
=> read solana keypair, convert to helium keypair

file_store/src/file_store.rs
Aws SDK for s3 provides a Paginator that we can use and not have to manage the state ourselves.
=> use aws s3 sdk built in paginator

boost_manager/src/main.rs, file_store/src/settings.rs, iot_packet_verifier/src/main.rs, mobile_config/tests/gateway_service.rs, mobile_packet_verifier/src/main.rs, mobile_verifier/src/main.rs, mobile_verifier/tests/integrations/rewarder_poc_dc.rs, poc_entropy/src/main.rs, reward_index/src/main.rs
=> chore: fix some typos in comment

tls_init/src/lib.rs
If a project pulls in `oracle` dependencies from multiple sources (git  vs. local path), `ctor` will not dedupe the installer running because  they’re different bins. 
This change checks if AwsLcRs has already been installed by someone  else, and noops when that’s the case. Otherwise tries to install AwsLcRs as the default provider.
=> Check installed crypto provider before installing
